### ISSUE TITLE
[ Bug report ] Snippets absent locally

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1001]
## Required

**What is the issue?**

Snipsync snippets aren't being inserted for me in dev. And I can't find where `snipsync` is used? https://github.com/temporalio/documentation/search?q=snipsync

**How can we reproduce the issue?**

```
npm start (or npm build && npm serve)
open http://localhost:3000/docs/typescript/clients
```

<img width="684" alt="image" src="https://user-images.githubusercontent.com/251288/158735108-63c40c59-3b15-4478-8512-fde4998ff62c.png">

**What is the expected behavior?**

<img width="990" alt="image" src="https://user-images.githubusercontent.com/251288/158735242-289081a7-2e23-4177-83b9-db1b1835f954.png">

**Comment by flossypurse** [comment]
run `yarn snipsync` to merge the snippets locally.
run `yarn snipsync --clear` when you are done testing to remove the snippets (we don't check in synced snippets into the repo)
