### ISSUE TITLE
[ Documentation request ] Workflow Archival 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#1007]
1. On https://docs.temporal.io/docs/concepts/what-is-archival/
Please provide a link to https://docs.temporal.io/docs/server/archive-data/ which includes more info on archival

2. https://docs.temporal.io/docs/server/archive-data/

a) Overview Section:
(replace if possible with following text):

          Archival automatically moves workflow histories (history archival) and visibility records (visibility archival) from persistence to 
          a secondary data store after the retention period, thus allowing users to keep workflow history and visibility records as long as 
          necessary. 
(also add link there to workflow retention if one exists if possible)

3. In the FAQ under the "Is there a generic query syntax for the visibility archiver?" section:
This section is imo incorrect, there is specific query syntax for each out-of-box provider we set. We should link to:
https://github.com/temporalio/temporal/tree/master/common/archiver/s3store#visibility-query-syntax
and 
https://github.com/temporalio/temporal/tree/master/common/archiver/gcloud#visibility-query-syntax

4. In the FAQ section please add following:

        When does archival happen?
        Currently history archival happens after the retention period, while visibility archival happens immediately after workflow 
        closes. This is a current implementation detail in Temporal that will be improved in the future. In order to be sure that both 
        visibility and history archival data is available, archived data should only be checked after the retention period.

**Comment by tsurdilo** [comment]
Here are some forum posts related to this request:
https://community.temporal.io/t/difference-between-archival-and-inline-archival/3487
https://community.temporal.io/t/temporal-ui-archival-tab-glitches/3740

**Comment by aarohib** [comment]
Also: https://cadenceworkflow.io/docs/concepts/archival/#running-in-production

**Comment by flossypurse** [comment]
per @tsurdilo  

https://cadenceworkflow.io/docs/concepts/archival/#faq

https://github.com/temporalio/temporal/blob/master/config/development.yaml#L116

https://github.com/temporalio/temporal/tree/master/common/archiver/gcloud

https://github.com/temporalio/temporal/tree/master/common/archiver/filestore
