### ISSUE TITLE
[ Documentation request ] Missing info on Elasticsearch docs 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#1021]
Page: https://docs.temporal.io/docs/clusters/how-to-integrate-elasticsearch-into-a-temporal-cluster/
Section: Create Index schema and index - https://docs.temporal.io/docs/clusters/how-to-integrate-elasticsearch-into-a-temporal-cluster/#create-index-schema-and-index

This section is missing the command to run, just says "Run the following commands to create the index schema and index:" without the actual command. Please add.

**Comment by flossypurse** [comment]
Awesome. That is because some deleted the source snippets: https://github.com/temporalio/temporal/blob/master/docker/auto-setup.sh

**Comment by flossypurse** [comment]
fyi, now in this repo https://github.com/temporalio/docker-builds/blob/main/docker/auto-setup.sh#L267
