### ISSUE TITLE
tctl workflow list commands need update

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#1132]
Page: https://docs.temporal.io/docs/tctl/workflow/list#--latest_time

The two samples here use dash instead of underscore for the latest_time command
Please change to underscore

Also maybe instead of using "10second" we could just do "10s" as that works as well and is shorter

**Comment by DJSanti** [comment]
This is also an ongoing change that needs to be made across tctl

**Comment by DJSanti** [comment]
I'll start it back up once 1.17 drops

**Comment by flossypurse** [comment]
Reopening.
The examples need to match the header - and the header must match the currently support version - which I think is still 1.16?

![Screen Shot 2022-06-15 at 1 38 25 PM](https://user-images.githubusercontent.com/34380806/173910490-09931089-21d0-41b3-bd46-7c8b95929cd7.png)
