### ISSUE TITLE
How to test Workflow Definitions in Go - FIXME [ Documentation request ] 

### ISSUE THREAD

**Issue by StewartJ-SSG** [temporalio/documentation#1160]
# Brief description

The page: [How to test Workflow Definitions in Go](https://docs.temporal.io/docs/go/how-to-test-workflow-definitions-in-go/) has a misleading / incorrect example in AfterTest()

The example has the following:
`
        s.env.AssertExpectations(s.T())
`

but AssertExpectations() returns a bool, it doesn't cause any side effects - so having the method output not being interpreted in any kind of code logic misleads newbies (like me) into assuming that it is actually causing an assertion failure on false - which it isn't.

#  Your recommended content

Giving a working example. Since I've still been unable to AssertExpectations to successfully produce a false outcome when the expectations weren't met, I'm still not sure how to properly use it. Having correct docs would help.

**Comment by StewartJ-SSG** [comment]
I've dug into the code and found that not only does it return a bool, but there is actually a call to t.Errorf() if there are missed calls.

**Comment by flossypurse** [comment]
@StewartJ-SSG did you mean to close this?
Happy to pick it back up if you did not.

**Comment by jasonestewart** [comment]
hey @flossypurse - yes, the documentation that exists does indeed show the correct usage - my tests weren't correctly logging all of the expectations - none were expected so no assertions were triggered. Once I figured out what was happening, AssertExpectations() started giving me the error I was expecting. RTFM.
