### ISSUE TITLE
[ Documentation request ] Design review process

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1227]
# Brief description

I think it would be nice to have a design review template companies can use internally when deciding how to build something with Temporal. Inspired by this SO question: https://stackoverflow.com/questions/72493152/what-should-i-consider-when-using-cadence-temporal-to-design-a-new-project

**Comment by axfelix** [comment]
Agree this is a priority for Dev Rel — closing this issue since it's not getting any more attention here, but happy to continue this conversation!
