### ISSUE TITLE
[ Documentation request ]  typescript cancellation scopes documentation references missing code snippets

### ISSUE THREAD

**Issue by kheyse-oqton** [temporalio/documentation#1269]
# Brief description

Current documentation for typescript cancellation scopes references code snippets, but the snippets are missing. 

[Provide a description of your documentation request.](https://docs.temporal.io/typescript/cancellation-scopes/#internal-cancellation-example)

**Comment by axfelix** [comment]
Closing — this refers to an older release of docs.
