### ISSUE TITLE
[ Bug report ] versioned_docs system UX

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1272]
## Editing experience

**What is the issue?**

- go to https://docs.temporal.io/
- click "edit this page"
- I'm taken to https://github.com/temporalio/documentation/blob/master/versioned_docs/version-june-2022/index.md

**What is the expected behavior?**

I'm taken to https://github.com/temporalio/documentation/blob/master/docs/index.md

## Local experience

**What is the issue?**

When I edit `/docs` locally, I don't see it reflected in `localhost:3000` unless I prefix `/next` to the path.

**Solution**

- Add to https://github.com/temporalio/documentation/blob/master/CONTRIBUTING.md#preview-changes-locally an explanation of what content `npm start` is showing.
- Have `npm start` log a message saying it's showing `versioned_docs/` and how to have it show `docs/`

**Comment by flossypurse** [comment]
This is the expected behavior - because the documentation is versioned.

**Comment by flossypurse** [comment]
That depends.

But the edit links take you to the place you need to go to edit that page.

Everything at the `/` path is coming from `versioned_docs/june-2022` 

So that is why the edit link takes you there.
