### ISSUE TITLE
Add `master` branch protection rules

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1300]
Currently it appears there are either 0 or 1 (maybe cla) actions that are required to pass before merging to master. Do we want to add more? I'd at least make sure the build and deploy works.

- https://github.com/temporalio/documentation/settings/branches
- edit/add `master` branch protection rule
- `Require status checks to pass before merging`

**Comment by flossypurse** [comment]
Ya, good call.
Done.

<img width="793" alt="Screen Shot 2022-07-17 at 8 26 35 PM" src="https://user-images.githubusercontent.com/34380806/179430940-cba0ea48-80e3-46c4-a7e4-5eddd83703b0.png">

**Comment by lorensr** [comment]
Is the CLA an option as well?

**Comment by flossypurse** [comment]
Oh, yes it is. Added that as well.
