### ISSUE TITLE
[ Documentation request ] Explain how to use `dashboards`

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1329]
https://github.com/temporalio/dashboards/

**Comment by lorensr** [comment]
@robholland if you wanted to write some content in a comment, I'd be happy to convert it to a docs PR ☺️

**Comment by robholland** [comment]
Added some notes to the README for now: https://github.com/temporalio/dashboards/pull/23 Usage will improve soon but I didn't want to block that work before giving users the current workflow.
