### ISSUE TITLE
[ Documentation request ] tctl Global modifiers

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1384]
# Brief description
https://docs.temporal.io/tctl/#global-modifiers should be its own page and not nested under the `What is ...` section of the docs, as Global modifiers are equivalent to any other tctl argument.

Provide a description of your documentation request.

#  Your recommended content

I would imagine this is similar to how [Environment variables](https://docs.temporal.io/tctl/environment-variables) look like.
Where the TOC shows:

* Install
* Enviroment variables
* Global modifiers

Add your recommended content here. Add the content directly to this page or add links to drafts.
Documentation requests that are made without any recommendations could take longer to process.

**Comment by djmagee** [comment]
Another take is that the global modifiers apply to the `tctl` command and thus should appear on the same page, paralleling the presence of subcommand modifiers on the same page as the subcommand.

Having said that, the global-modifier list has grown to the point that moving it to its own page and then pulling it into the main `tctl` page makes a lot of sense.

**Comment by rachfop** [comment]
Closing as it is tracked internally or completed.
