### ISSUE TITLE
[ Documentation request ] How to send a task to a specified worker

### ISSUE THREAD

**Issue by zhanglongOsborne** [temporalio/documentation#1390]
# Brief description
How to send a task to a specified worker？

#  Your recommended content

**Comment by flossypurse** [comment]
Hi @zhanglongOsborne, If you need to specify a specific Worker, then that Worker should also have a dedicated Task Queue.

You can then specify the Task Queue and know that only that Worker is listening to it:
https://docs.temporal.io/tasks#task-routing
