### ISSUE TITLE
tctl install doc: make tctl ?

### ISSUE THREAD

**Issue by marchmallow** [temporalio/documentation#1396]
# Brief description

In https://github.com/temporalio/documentation/blob/master/docs/tctl/how-to-install-tctl.md it says:

```
Build it locally:
Clone the [Temporal Server repo](https://github.com/temporalio/temporal).
Run make tctl.
```

But this does not work, see if I try make from temporal top level dir:

```
% make tctl
make: *** No rule to make target `tctl'.  Stop.
```
#  Your recommended content

There is a `update-tctl` target, not sure if that is what the doc should be changed to:

```
% make update-tctl
Install/update tctl...
go: downloading github.com/temporalio/tctl v1.16.2
go: downloading github.com/temporalio/tctl-kit v0.0.0-20220512165751-9c751176dd14
go: downloading go.temporal.io/server v1.16.1-0.20220520210750-d3f3a2989dd7
...
```

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/issues/1396 by removing `tctl` compile deprecation as it is being deprecated -- it can still be installed as a binary.
