### ISSUE TITLE
[ Documentation request ] tctl namespace describe

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1408]
# Brief description

[This page.](https://docs.temporal.io/tctl/namespace/describe)
`--namespace_id` does not display its alias, yet the example displays an alias.

`$ tctl --ns canary-namespace n desc`

`tctl` = the tctl command
`--ns` = ? [docs show the alias being](https://docs.temporal.io/tctl/namespace/) `-n`.
`canary-namespace` = is it clear that this is a [placeholder](https://developers.google.com/style/placeholders?hl=en) for one's Namespace Name?
`n` = Alias for Namespace
`desc` = Alias for describe

#  Your recommended content

Can you clarify what the sample is doing and add alias for the commands.
I would also not use alias for sample/examples to make it clear what the actions are.

**Comment by djmagee** [comment]
The `--ns` alias is for the `--namespace` global modifier. (See https://docs.temporal.io/tctl/#--namespace.) Most of the other tctl examples don't use global modifiers or aliases, so the example results might be clearer if the command were `tctl namespace describe --namespace_id canary-namespace`.

Also important: `yourtech.io` is a valid domain name. Better to use `example.com`, which is reserved by IANA for this kind of use.

**Comment by rachfop** [comment]
Closing as it is tracked internally or completed.
