### ISSUE TITLE
[ Bug report ] SDK Reference links are somewhat non-discoverable

### ISSUE THREAD

**Issue by afitz0** [temporalio/documentation#1417]
## Required

**What is the issue?**
1. I frequently type in `docs.temporal.io` to look for the SDK reference docs.
2. My next step is to expand the References header.
3. Here I'll fork: sometimes I next click on "SDK Metrics" -- which isn't what I want -- sometimes on "External Resources" (which is also not what I want).
4. Typically I spin, not sure what to do next until I remember that if I click on the References header (NOT expanding the section) that's where (some of them; where's PHP?) are.
5. (Searching for "SDK Reference" or "Go Reference" also does NOT surface the reference pages)

**How can we reproduce the issue?**
1. Go to docs.temporal.io
2. Avoid clicking on "Reference" in the left-nav
3. Try to find a language's SDK reference

**What is the expected behavior?**
SDK reference is easily and quickly (if not trivially) discoverable in the nav or in the docs search.

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**
![Screen Shot 2022-08-16 at 9 38 48 AM](https://user-images.githubusercontent.com/400613/184932850-59b3b808-821b-48be-9fd9-1748743471cf.png)

**Comment by lorensr** [comment]
Think there might not be one: https://github.com/temporalio/sdk-php/issues/213

How's this?

![image](https://user-images.githubusercontent.com/251288/184941866-721d7905-033c-4af9-bf06-ac15c2413f63.png)

**Comment by afitz0** [comment]
> How's this?
> 
> ![image](https://user-images.githubusercontent.com/251288/184941866-721d7905-033c-4af9-bf06-ac15c2413f63.png)

LGTM, thanks!
