### ISSUE TITLE
[Foundations] Register multiple types is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1431]
# [Register multiple types](https://docs.temporal.io/application-development/foundations?lang=typescript#register-multiple-types) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-worker-create

WorkerOptions.workflowsPath https://typescript.temporal.io/api/interfaces/worker.workeroptions/#workflowspath
WorkerOptions.activities https://typescript.temporal.io/api/interfaces/worker.workeroptions/#activities
