### ISSUE TITLE
[Foundations] Activity return values is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1433]
# [Activity return values](https://docs.temporal.io/application-development/foundations?lang=python#activity-return-values) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
This content does appear present to me. Am I misunderstanding?
