### ISSUE TITLE
[Foundations] Customize Workflow Type is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1438]
# [Customize Workflow Type](https://docs.temporal.io/application-development/foundations?lang=typescript#customize-workflow-type) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/251288/186951690-c7cefe48-21bd-40d0-988c-cab2807599c1.png">

"custom" and "customize" feel weird. It's a necessary part of a workflow definition. 

suggest changing to:

### Workflow Type

Workflows have a Type (also referred to as the Workflow *name*).

TS tab:

In TS, the Workflow Type is the Workflow function name. In this snippet, the Type is `"helloWorld"`

typescript-workflow-type
