### ISSUE TITLE
[Features] Send Signal from Client is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1440]
# [Send Signal from Client](https://docs.temporal.io/application-development/features?lang=python#send-signal-from-client) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
```python
await my_workflow_handle.signal(MyWorkflow.my_signal, "my signal arg")
```

https://github.com/temporalio/samples-python/blob/7f2f9b7928a8dc8793616f54db3fb2a83f85d82f/hello/hello_signal.py#L61
