### ISSUE TITLE
[Features] Send Signal from Workflow is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1442]
# [Send Signal from Workflow](https://docs.temporal.io/application-development/features?lang=python#send-signal-from-workflow) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
```python
@workflow.defn
class MyWorkflow:
    @workflow.run
    async run(self) -> None:
        handle = workflow.get_external_workflow_handle_for(OtherWorkflow.run, "other-workflow-id)
        await handle.signal(OtherWorkflow.other_signal, "other signal arg")
```
