### ISSUE TITLE
[Features] Define Query is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1445]
# [Define Query](https://docs.temporal.io/application-development/features?lang=typescript#define-query) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-define-query

defineQuery https://typescript.temporal.io/api/namespaces/workflow/#definequery

and change the following sections to:

typescript-handle-query

handleQuery https://typescript.temporal.io/api/interfaces/workflow.workflowinboundcallsinterceptor/#handlequery

typescript-send-query

WorkflowHandle.query https://typescript.temporal.io/api/interfaces/client.workflowhandle/#query
