### ISSUE TITLE
[Features] Workflow Run Timeout is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1446]
# [Workflow Run Timeout](https://docs.temporal.io/application-development/features?lang=typescript#workflow-run-timeout) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-run-timeout

`WorkflowOptions.workflowRunTimeout` https://typescript.temporal.io/api/interfaces/client.workflowoptions/#workflowruntimeout
