### ISSUE TITLE
[Features] Workflow Task Timeout is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1448]
# [Workflow Task Timeout](https://docs.temporal.io/application-development/features?lang=typescript#workflow-task-timeout) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-task-timeout

`WorkflowOptions.workflowTaskTimeout` https://typescript.temporal.io/api/interfaces/client.workflowoptions/#workflowtasktimeout
