### ISSUE TITLE
[Features] Workflow Retry Policy is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1450]
# [Workflow Retry Policy](https://docs.temporal.io/application-development/features?lang=typescript#workflow-retry-policy) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-retry-workflow

`WorkflowOptions.retry` https://typescript.temporal.io/api/interfaces/client.workflowoptions/#retry
