### ISSUE TITLE
[Features] Async Activity Completion is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1455]
# [Async Activity Completion](https://docs.temporal.io/application-development/features?lang=typescript#async-activity-completion) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-activity-complete-async

`AsyncCompletionClient.complete` https://typescript.temporal.io/api/classes/client.AsyncCompletionClient#complete
