### ISSUE TITLE
[Features] Child Workflows is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1458]
# [Child Workflows](https://docs.temporal.io/application-development/features?lang=python#child-workflows) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
The full sample is at https://github.com/temporalio/samples-python/blob/main/hello/hello_child_workflow.py.

Executing a child workflow:

```python
await workflow.execute_child_workflow(MyWorkflow.run, "my child arg", "my-child-id")
```

Of course you can just `await workflow.start_child_workflow(...` which returns a task/handle to the child workflow once started which can be awaited on for its result or `signal` can be called to signal it.
