### ISSUE TITLE
[Features] Child Workflows is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1459]
# [Child Workflows](https://docs.temporal.io/application-development/features?lang=typescript#child-workflows) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
typescript-child-workflow

- `startChild` https://typescript.temporal.io/api/namespaces/workflow/#startchild
- `executeChild` https://typescript.temporal.io/api/namespaces/workflow/#executechild
