### ISSUE TITLE
[Features] Parent Close Policy is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1460]
# [Parent Close Policy](https://docs.temporal.io/application-development/features?lang=python#parent-close-policy) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
This should not be an entire section IMO. This is one tiny setting on a function.

This is just setting the `parent_close_policy` keyword argument on `client.start_child_workflow`/`client.execute_child_workflow`.
