### ISSUE TITLE
[Features] Parent Close Policy is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1461]
# [Parent Close Policy](https://docs.temporal.io/application-development/features?lang=typescript#parent-close-policy) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
`typescript-child-workflow`

https://typescript.temporal.io/api/interfaces/workflow.ChildWorkflowOptions#parentclosepolicy
