### ISSUE TITLE
[Features] Continue-As-New is missing in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1462]
# [Continue-As-New](https://docs.temporal.io/application-development/features?lang=typescript#continue-as-new) is missing is TypeScript
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by lorensr** [comment]
`typescript-continue-as-new-workflow`

**Comment by lorensr** [comment]
i like also linking to the API ref: https://typescript.temporal.io/api/namespaces/workflow/#continueasnew
