### ISSUE TITLE
[Observability] Metrics is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1465]
# [Metrics](https://docs.temporal.io/application-development/observability?lang=python#metrics) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
(this may change and is experimental for now, ref https://github.com/temporalio/sdk-python/issues/125)

Currently, metrics are configured globally be setting a Prometheus endpoint _before_ any other Temporal code is used. To expose a Prometheus endpoint on port 9000:

```python
from temporalio.bridge.telemetry import init_telemetry, TelemetryConfig, PrometheusMetricsConfig

init_telemetry(TelemetryConfig(prometheus_metrics=PrometheusMetricsConfig(bind_address="0.0.0.0:9000")))
```

**Comment by cretz** [comment]
@rachfop - This just changed in Python 1.0.0 release to be:

```python
from temporalio.runtime import Runtime, TelemetryConfig, PrometheusConfig

# Create a new runtime that has telemetry enabled. Create this first to avoid
# the default Runtime from being lazily created.
new_runtime = Runtime(telemetry=TelemetryConfig(metrics=PrometheusConfig(bind_address="0.0.0.0:9000")))
my_client = await Client.connect("my.temporal.host:7233", runtime=new_runtime
```

**Comment by RonaldGalea** [comment]
> @rachfop - This just changed in Python 1.0.0 release to be:
> 
> ```python
> from temporalio.runtime import Runtime, TelemetryConfig, PrometheusConfig
> 
> # Create a new runtime that has telemetry enabled. Create this first to avoid
> # the default Runtime from being lazily created.
> new_runtime = Runtime(telemetry=TelemetryConfig(metrics=PrometheusConfig(bind_address="0.0.0.0:9000")))
> my_client = await Client.connect("my.temporal.host:7233", runtime=new_runtime)
> ```

What is the client needed for there @cretz ?

**Comment by spacether** [comment]
Why are we binding to a 0 ip address?
docs do not describe what it is used for:
https://python.temporal.io/temporalio.runtime.PrometheusConfig.html#bind_address
Is this referring to the temporal server, or is this referring to the sending server and port that metrics are exposed on?
