### ISSUE TITLE
[Observability] Tracing is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1467]
# [Tracing](https://docs.temporal.io/application-development/observability?lang=python#tracing) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
I will create a full example in https://github.com/temporalio/samples-python/issues/12, but for now: https://github.com/temporalio/sdk-python/blob/07da1b908c621cafd59d48470fc0324392d3d12e/README.md?plain=1#L732-L742
