### ISSUE TITLE
[Observability] Custom logging is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1468]
# [Custom logging](https://docs.temporal.io/application-development/observability?lang=python#custom-logging) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
This is built-in to Python. See https://docs.python.org/3/library/logging.html and associated pages for information on how to customize logging.
