### ISSUE TITLE
[Observability] Tracing is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1469]
# [Tracing](https://docs.temporal.io/application-development/observability?lang=java#tracing) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
See the Readme of the opentracing module: https://github.com/temporalio/sdk-java/blob/master/temporal-opentracing/README.md#usage

Sample client side: https://github.com/temporalio/samples-java/blob/708324ffd1599df4d593b411e9516424be096033/src/main/java/io/temporal/samples/tracing/Starter.java#L43

Sample worker: https://github.com/temporalio/samples-java/blob/708324ffd1599df4d593b411e9516424be096033/src/main/java/io/temporal/samples/tracing/TracingWorker.java#L47
