### ISSUE TITLE
[Observability] Custom logging is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1471]
# [Custom logging](https://docs.temporal.io/application-development/observability?lang=java#custom-logging) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
In workflow code users should be using Workflow.getLogger to obtain a standard slf4j logger like it's done here: https://github.com/temporalio/samples-java/blob/effc7838e0665076bf0e35fcd78b3107afb315f3/src/main/java/io/temporal/samples/dsl/DynamicDslWorkflow.java#L50
After that they can log using standard slf4j logger interface. Such logs will be replay-aware and will not be repeated during replays.
Slf4J is the most popular java logging facade. Users need to supply their own logger implementation and config. The same way they do in any other Java apps that use slf4j and logging.
