### ISSUE TITLE
[Observability] Set custom search attributes is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1475]
# [Set custom search attributes](https://docs.temporal.io/application-development/observability?lang=java#set-custom-search-attributes) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
Custom search attributes can be initially set on WorkflowOptions like this:

https://github.com/temporalio/samples-java/blob/708324ffd1599df4d593b411e9516424be096033/src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java#L178

```
    WorkflowOptions workflowOptions =
        WorkflowOptions.newBuilder()
            .setSearchAttributes(saMap)
            .build();
```

Where `saMap` is a Map<String, ?> from SA name to a value (`String`, `Long`, `Integer`, `Boolean`, `Double`, `OffsetDateTime`
