### ISSUE TITLE
[Observability] Upsert custom search attributes is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1477]
# [Upsert custom search attributes](https://docs.temporal.io/application-development/observability?lang=java#upsert-custom-search-attributes) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
Workflow code can call  `Workflow.upsertSearchAttributes(Map<String, ?> searchAttributes)` Map here is the same as a map in https://github.com/temporalio/documentation/issues/1475
