### ISSUE TITLE
[Observability] Replays is missing in Python

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1479]
# [Replays](https://docs.temporal.io/application-development/observability?lang=python#replays) is missing is Python
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by cretz** [comment]
https://github.com/temporalio/sdk-python/blob/07da1b908c621cafd59d48470fc0324392d3d12e/README.md?plain=1#L716-L730
