### ISSUE TITLE
[Observability] Remove search attributes is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1480]
# [Remove search attributes](https://docs.temporal.io/application-development/observability?lang=java#remove-search-attributes) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
To remove a SA in Java, `io.temporal.common.SearchAttribute#UNSET_VALUE` value can be used in upsert map (see https://github.com/temporalio/documentation/issues/1477) for the SA name.
