### ISSUE TITLE
[Observability] Replays is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1481]
# [Replays](https://docs.temporal.io/application-development/observability?lang=java#replays) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
We don't have a sample with WorkflowReplayer. 
But here we replay from a history persistent in a file:
https://github.com/temporalio/sdk-java/blob/37a0e463fae2312882b5c946f423a0dbf85f9666/temporal-sdk/src/test/java/io/temporal/workflow/childWorkflowTests/ChildWorkflowAsyncRetryTest.java#L84

WorkflowReplayer has a lot of methods allowing to replay from all kinds of sources:

```
  /**
   * Replays workflow from a file
   */
  public static void replayWorkflowExecution(
      File historyFile, Class<?> workflowClass, Class<?>... moreWorkflowClasses)


  /**
   * Replays workflow from a json serialized history. The json should be in the format:
   *
   * <pre>
   * {
   *   "workflowId": "...",
   *   "runId": "...",
   *   "events": [
   *     ...
   *   ]
   * }
   * </pre>
   */
  public static void replayWorkflowExecution(
      String jsonSerializedHistory, Class<?> workflowClass, Class<?>... moreWorkflowClasses)
```

Or from the raw History object that users may obtain from calling the server for the events or in their testing framework:

```
  /**
   * Replays workflow from a resource that contains a json serialized history.
   *
   * @param history object that contains the workflow ids and the events.
   * @param worker existing worker with registered workflow implementations.
   * @throws Exception if replay failed for any reason.
   */
  public static void replayWorkflowExecution(WorkflowExecutionHistory history, Worker worker)
```
