### ISSUE TITLE
Add section: What can I do to a Workflow?

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1487]
I think it would be helpful to see a list of things I can do to a Workflow Execution, what they do, and why I might want to do them. 

- start
- get result
- describe
- query
- signal
- cancel
- terminate

Some info to include:

- What Cancelling does (& note that you can't request cancellation multiple times)
- When to Cancel vs Terminate

**Comment by axfelix** [comment]
@lorensr Our Workflow docs are *sort of* structured this way now — are you proposing having a sort of table of contents of all the H1 elements in the right nav, listed in the first section of this page: https://docs.temporal.io/workflows?

**Comment by lorensr** [comment]
Not of all H1s. A section under `What is a Workflow Execution?` titled `What are the operations I can perform on a Workflow Execution?` with the above list of links to other sections.
