### ISSUE TITLE
[ Bug report ] broken link "Requirements for client certificates."

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#1501]
## Required

**What is the issue?**

On the page https://docs.temporal.io/cloud/how-to-manage-certificates-in-temporal-cloud/

The text "Ensure that your certificates meet the `Requirements for client certificates`" the text `Requirements for client certificates` point to https://docs.temporal.io/cloud/how-to-manage-certificates-in-temporal-cloud/#requirements-for-client-certificates, which does not exist

**How can we reproduce the issue?**

**What is the expected behavior?**

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by djmagee** [comment]
Thanks for catching this, @antmendoza!
