### ISSUE TITLE
[ Bug report ] TypeScript / JavaScript whitespace

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1503]
## Required

**What is the issue?**
When switching between TypeScript/JavaScript code samples, I've noticed that TypeScript uses 4 spaces `    `, whereas JavaScript only uses 2 spaces `  `.
**How can we reproduce the issue?**

For example, [on this page](https://docs.temporal.io/application-development/observability/?lang=js#set-custom-search-attributes).
## TypeScript

```typescript
const handle = await client.start(example, {
    taskQueue: 'search-attributes',
    workflowId: 'search-attributes-example-0',
    searchAttributes: {
      CustomIntField: [2],
      CustomKeywordField: ['keywordA', 'keywordB'],
      CustomBoolField: [true],
      CustomDatetimeField: [new Date()],
      CustomStringField: [
        'String field is for text. When queried, it will be tokenized for partial match. StringTypeField cannot be used in Order By',
      ],
    },
  });

  const { searchAttributes } = await handle.describe();
```

## JavaScript
```javascript
const handle = await client.start(example, {
  taskQueue: 'search-attributes',
  workflowId: 'search-attributes-example-0',
  searchAttributes: {
    CustomIntField: [2],
    CustomKeywordField: ['keywordA', 'keywordB'],
    CustomBoolField: [true],
    CustomDatetimeField: [new Date()],
    CustomStringField: [
      'String field is for text. When queried, it will be tokenized for partial match. StringTypeField cannot be used in Order By',
    ],
  },
});

const { searchAttributes } = await handle.describe();
```

Because of that, it appears that TypeScript isn't hightlighting the "keys" or var names and JavaScript does.

**What is the expected behavior?**

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

## TypeScript

<img width="822" alt="Screen Shot 2022-08-24 at 8 23 15 AM" src="https://user-images.githubusercontent.com/64233065/186458153-1930dbcd-fe30-4ee1-a768-163c5fa2b948.png">

## JavaScript

<img width="822" alt="Screen Shot 2022-08-24 at 8 23 22 AM" src="https://user-images.githubusercontent.com/64233065/186458138-ed52f38f-ccf0-4e70-823e-2ee81173a4b0.png">

**Comment by lorensr** [comment]
It's due to the snippet comment not starting indented:

![image](https://user-images.githubusercontent.com/251288/186461890-ca2e3b55-88ec-4b6a-aa3e-1a2ab507f46f.png)


@vkarpov15 are you up for looking at removing the indentation? Related: #1379
