### ISSUE TITLE
[ Documentation request ] Improve the standard visibility documentation 

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#1513]
# Brief description

Improve the standard visibility documentation https://docs.temporal.io/concepts/what-is-standard-visibility/

#  Your recommended content

It would be nice to have a table similar to https://docs.temporal.io/concepts/what-is-a-search-attribute/#default-search-attributes for search attributes for standard visibility. 

I know that the documentation mention "Workflow Type, Workflow Id, or Run Id" but sometimes it is not clear to the user how to use them.

Also, it would be helpful to have some examples, for example:
- "Open Workflow Executions can be filtered by a time constraint" i.e `StartTime BETWEEN "2022-08-29T14:47:29+02:00" AND "2024-08-30T15:47:29+02:00"`

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/pull/2387
