### ISSUE TITLE
[ Bug report ] broken link in "Application development - Foundations"

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#1522]
## Required

**What is the issue?**

On this page https://docs.temporal.io/application-development/foundations

`How to start an Activity Execution` points to  https://docs.temporal.io/application-development/foundations#start-activity-execution, which does not exist. 
I guess that the right link is https://docs.temporal.io/application-development/foundations#activity-execution

**How can we reproduce the issue?**

**What is the expected behavior?**

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by axfelix** [comment]
Closing — this was fixed in a docs migration at some point.
