### ISSUE TITLE
New batch operation documentation

### ISSUE THREAD

**Issue by yux0** [temporalio/documentation#1550]
# Brief description

Add new new batch operation documentation after this feature supports in tctl v2.

#  Your recommended content

1. StartBatchOperation
2. StopBatchOperation
3. DescribeBatchOperation
4. ListBatchOperations

**Comment by yux0** [comment]
TCTL task is tracking in https://github.com/temporalio/tctl/issues/270

**Comment by axfelix** [comment]
Closing as this is handled in the current `temporal` CLI docs.
