### ISSUE TITLE
[ Bug report ] broken link when search "tctl"

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#1563]
## Required

**What is the issue?**

When I search tctl, the first result that is shown is broken. It points to https://docs.temporal.io/tctl/how-to-use-tctl/

<img width="884" alt="Screenshot 2022-09-09 at 14 10 41" src="https://user-images.githubusercontent.com/514932/189347447-5676c3c3-9ee9-446d-899f-0169a29f3aa8.png">

**How can we reproduce the issue?**

**What is the expected behavior?**

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by flossypurse** [comment]
Site search reindexed last Friday - which fixed this issue I believe.
![Screen Shot 2022-09-13 at 4 13 22 PM](https://user-images.githubusercontent.com/34380806/190018679-f6279f81-f239-445c-b942-bc598ca2a973.png)
