### ISSUE TITLE
[ Bug report ] Wrong time unit specified in documentation about SDK metrics

### ISSUE THREAD

**Issue by Zylius** [temporalio/documentation#1577]
I'm not sure if this should be a bug report or a functionality request.

The `activity_schedule_to_start_latency` metric is specified [as being in milliseconds](https://docs.temporal.io/references/sdk-metrics/?_ga=2.198604655.1114247673.1663057465-359618555.1646691645#activity_schedule_to_start_latency), when it's actually in seconds. 

See discussion [here](https://community.temporal.io/t/docs-inaccuracy-latencies-in-microseconds/5953/5).

**Comment by axfelix** [comment]
Thanks for reporting this and sorry for taking so long getting to it! Fixed in https://github.com/temporalio/documentation/pull/2386
