### ISSUE TITLE
[ Documentation request ]  Connect to a Cluster Snip-Sync 🚀 

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1588]
# Brief description

The Temporal Docs team were able to connect to the Temporal Cloud using MTLs 🚀. 

With that information, we took our learnings to [rewrite the introduction page and remove a lot of fluff.](https://docs.temporal.io/application-development/foundations#connect-to-a-cluster) (Thanks Chad for pointing this out in a prior section 😎.)

We would like the content reviewed and have the **following requirements added to the samples' repo**, so we can use snip-sync.

Each code snippet should have an MVP of:
1. Connect to the Cloud with MTLs.

Each code snippet should have a comments (either in `#` or `//`) that shows how to connect to Temporalite (or default).
1. Default Namespace
2. Default connection

(optional) Each code snippet can provide alternative ways to connect to a remote cluster in a comment:
1. TLS
2. Sever Root CA Cert

- [ ] Go 🐱 
- [ ] Java 🌵 
- [ ] PHP 🍰 
- [ ] Python 🤙 
- [ ] TypeScript 🍾 

- [x] [related issue](https://github.com/temporalio/documentation/issues/1412)

**Comment by lorensr** [comment]
I'll review general content and do TS snippet.

**Comment by rachfop** [comment]
Closing as it is merged.
