### ISSUE TITLE
[ Documentation request ]  How to customize an Activity Name in TypeScript

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1591]
# Brief description

Need to explain further on how to customize an Activity Name or Type in TypeScript, rather than how to set the Activity Name.

Provide a description of your documentation request.

#  Your recommended content

https://typescript.temporal.io/api/interfaces/worker.workeroptions/#activities

Add your recommended content here. Add the content directly to this page or add links to drafts.
Documentation requests that are made without any recommendations could take longer to process.

**Comment by lorensr** [comment]
https://github.com/temporalio/documentation/pull/1581/files#r973488397

**Comment by rachfop** [comment]
Closing as it is merged.
