### ISSUE TITLE
[ Documentation request ] Describe Standard Visibility List Filter

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1601]
https://docs.temporal.io/visibility/#advanced-visibility

and 

https://docs.temporal.io/visibility/#list-filter

say that Advanced Vis is required for use of List Filter. @tsurdilo says that there is a limited subset of List Filter that works with Standard Vis.

**Comment by axfelix** [comment]
@lorensr Is this request still outstanding, and am I reading it right that it's a pretty straightforward one — just a one-liner addition to clarify?

**Comment by lorensr** [comment]
Yeah, maybe just in `What is standard visibility?`, clarify that standard can use a limited List Filter:

<img width="976" alt="image" src="https://github.com/temporalio/documentation/assets/251288/94e9015d-9b99-4df2-960a-3ecf1aafe0b7">

**Comment by axfelix** [comment]
Tracking in https://temporalio.atlassian.net/browse/EDU-1243

**Comment by axfelix** [comment]
Done in https://github.com/temporalio/documentation/pull/2387
