### ISSUE TITLE
Font color is broken for me

### ISSUE THREAD

**Issue by mikhailshilkov** [temporalio/documentation#164]
My docs site looks like this:

![image](https://user-images.githubusercontent.com/1454008/96471142-4b3d3f00-122f-11eb-810b-c994f56c4db2.png)

I'm on the latest Firefox/macOS. Microsoft Edge displays the font color okay.

I tried reloading, F12 - disable cache - reload, wiped the browser cache - with no improvement. No network or script errors are visible in the console.

**Comment by underrun** [comment]
check incognito mode and/or dropping cookies for the docs site

**Comment by mfateev** [comment]
It looks like you accessed the old version of the site. I had a similar issue. I had to reset my browser to fix this.
