### ISSUE TITLE
[ Documentation request ] Temporal Cloud - Add documentation on how to remove users downgrade/upgrade their roles

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#1684]
# Brief description

The documentation mentions how to invite users to Temporal Cloud. (https://docs.temporal.io/cloud/how-to-get-started-with-temporal-cloud#invite-users-using-web-ui), it would be nice to have similar documentation on how to remove users from Temporal Cloud and how to downgrade/upgrade their roles

#  Your recommended content
Ad section "Manage users", similar to "Manage namespaces"

**Comment by djmagee** [comment]
Published as an expansion of https://docs.temporal.io/cloud/account-setup/users.
