### ISSUE TITLE
[ Bug report ] missing documentation "Manage Namespaces in Temporal Cloud using Temporal Cloud UI"

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#1685]
## Required

**What is the issue?**

Documentation mention for "Manage Namespaces in Temporal Cloud using Temporal Cloud UI" "This functionality is in development." https://docs.temporal.io/cloud/how-to-manage-namespaces-in-temporal-cloud#manage-namespaces-in-temporal-cloud-using-temporal-cloud-ui

I think the documentation should be updated, 

If I navigate to https://cloud.temporal.io/namespaces I can see a list of namespaces, and if I click the three dots, I can edit the namespace

**Comment by flossypurse** [comment]
Tracked in TW-65
