### ISSUE TITLE
[ Bug report ] tctl taskqueue

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1713]
## Required

**What is the issue?**
The [tctl commands](https://docs.temporal.io/tctl-v1/#tctl-commands) show that task queue is specified as:
tctl taskqueue

But the `-h` [help commands](https://docs.temporal.io/tctl-v1/#install) show that task queue is specified as:
`tctl taskqueue`
**How can we reproduce the issue?**

```bash
# run
tctl taskqueue -h
# then run
tctl task-queue -h
```

**What is the expected behavior?**

```bash
NAME:
   tctl task-queue - Operations on task queues

USAGE:
   tctl task-queue command [command options] [arguments...]

COMMANDS:
   describe, d         Describe pollers info of task queue
   list-partition, lp  List all the taskqueue partitions and the hostname for partitions
   help, h             Shows a list of commands or help for one command

OPTIONS:
   --help, -h  show help (default: false)
   
```

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by flossypurse** [comment]
Tracked in TW-71

**Comment by DJSanti** [comment]
it doesn't have a hyphen in v1.
What exactly is wrong here?
