### ISSUE TITLE
[ Bug report ] task-queue

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1714]
## Required

**What is the issue?**

[This page](https://docs.temporal.io/tctl-v1/taskqueue) calls task queue `task-queue` in the title but all the examples show it as `taskqueue`.

**How can we reproduce the issue?**

**What is the expected behavior?**

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by flossypurse** [comment]
Tracked in TW-71
