### ISSUE TITLE
[ Bug report ] alias for task-queue [next]

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1715]
## Required

**What is the issue?**

`tctl task-queue` alias in the helper script is set to `d`, but the docs show `desc`. 
Is there docs that can provide insight into this?

Also, `list-partition` is missing its alias in the docs. From the helper script it appears to be `lp`.

**How can we reproduce the issue?**

```bash
   tctl task-queue - Operations on task queues

USAGE:
   tctl task-queue command [command options] [arguments...]

COMMANDS:
   describe, d         Describe pollers info of task queue
   list-partition, lp  List all the taskqueue partitions and the hostname for partitions
   help, h             Shows a list of commands or help for one command

OPTIONS:
   --help, -h  show help (default: false)
```

**What is the expected behavior?**

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by flossypurse** [comment]
Tracked in TW-71
