### ISSUE TITLE
[ go ] Add code samples for missing content

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1787]
The following sections need code samples.

Provide a code sample per section by using the comment section to provide a code snippet. 
Mark the checkbox complete as sample code is added.

If the language does not support a feature, write “NA” or link/code to a related concept: for an example, see Go’s [Remove Search Attribute](https://docs.temporal.io/application-development/observability?lang=go#remove-search-attribute).

## Testing

  - [ ] [Assert In Workflow](https://docs.temporal.io/application-development/testing?lang=go#assert-in-workflow)
  - [ ] [Automatic Method](https://docs.temporal.io/application-development/testing?lang=go#automatic-method)
  - [ ] [Cancel An Activity](https://docs.temporal.io/application-development/testing?lang=go#cancel-an-activity)
  - [ ] [Listen To Heartbeats](https://docs.temporal.io/application-development/testing?lang=go#listen-to-heartbeats)
  - [ ] [Manual Method](https://docs.temporal.io/application-development/testing?lang=go#manual-method)
  - [ ] [Mock Activities](https://docs.temporal.io/application-development/testing?lang=go#mock-activities)
  - [ ] [Run An Activity](https://docs.temporal.io/application-development/testing?lang=go#run-an-activity)
  - [ ] [Run An Activity](https://docs.temporal.io/application-development/testing?lang=go#run-an-activity)
  - [ ] [Setting Up](https://docs.temporal.io/application-development/testing?lang=go#setting-up)
  - [ ] [Skip Time In Activities](https://docs.temporal.io/application-development/testing?lang=go#skip-time-in-activities)
  - [ ] [Skip Time](https://docs.temporal.io/application-development/testing?lang=go#skip-time)
  - [ ] [Test Frameworks](https://docs.temporal.io/application-development/testing?lang=go#test-frameworks)
  - [ ] [Test Workflows](https://docs.temporal.io/application-development/testing?lang=go#test-workflows)
  - [ ] [Workflow Context](https://docs.temporal.io/application-development/testing?lang=go#workflow-context)

## Features

  - [ ] [Environment Variables](https://docs.temporal.io/application-development/features#environment-variables)

**Comment by Quinn-With-Two-Ns** [comment]
[Environment Variables](https://docs.temporal.io/application-development/features#environment-variables)

Appears to no longer be part of the dev guide?

**Comment by rachfop** [comment]
Closing as it is tracked internally now.
