### ISSUE TITLE
[ php ] Add code samples for missing content

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1789]
The following sections need code samples.

Provide a code sample per section by using the comment section to provide a code snippet.
Mark the checkbox complete as sample code is added.

If the language does not support a feature, write “NA” or link/code to a related concept: for an example, see Go’s [Remove Search Attribute](https://docs.temporal.io/application-development/observability?lang=go#remove-search-attribute).

## Testing

- [ ] [Assert In Workflow](https://docs.temporal.io/application-development/testing?lang=php#assert-in-workflow)
- [ ] [Automatic Method](https://docs.temporal.io/application-development/testing?lang=php#automatic-method)
- [ ] [Cancel An Activity](https://docs.temporal.io/application-development/testing?lang=php#cancel-an-activity)
- [ ] [Listen To Heartbeats](https://docs.temporal.io/application-development/testing?lang=php#listen-to-heartbeats)
- [ ] [Manual Method](https://docs.temporal.io/application-development/testing?lang=php#manual-method)
- [ ] [Replay](https://docs.temporal.io/application-development/testing?lang=php#replay)
- [ ] [Run An Activity](https://docs.temporal.io/application-development/testing?lang=php#run-an-activity)
- [ ] [Setting Up](https://docs.temporal.io/application-development/testing?lang=php#setting-up)
- [ ] [Skip Time In Activities](https://docs.temporal.io/application-development/testing?lang=php#skip-time-in-activities)
- [ ] [Test Activities](https://docs.temporal.io/application-development/testing?lang=php#test-activities)
- [ ] [Test Frameworks](https://docs.temporal.io/application-development/testing?lang=php#test-frameworks)
- [ ] [Workflow Context](https://docs.temporal.io/application-development/testing?lang=php#workflow-context)

## Observability

- [ ] [Custom Logger](https://docs.temporal.io/application-development/observability#custom-logger)
- [ ] [Logging](https://docs.temporal.io/application-development/observability#logging)
- [ ] [Metrics](https://docs.temporal.io/application-development/observability#metrics)
- [ ] [Remove Search Attribute](https://docs.temporal.io/application-development/observability#remove-search-attribute)
- [ ] [Search Attributes](https://docs.temporal.io/application-development/observability#search-attributes)
- [ ] [Tracing](https://docs.temporal.io/application-development/observability#tracing)
- [ ] [Visibility](https://docs.temporal.io/application-development/observability#visibility)

## Features

- [ ] [Mutable Side Effects](https://docs.temporal.io/application-development/features#mutable-side-effects)
- [ ] [Namespaces](https://docs.temporal.io/application-development/features#namespaces)
- [ ] [Side Effects](https://docs.temporal.io/application-development/features#side-effects)

**Comment by roxblnfk** [comment]
Documentation drafts to be moved into documentation site:
- [ ] https://github.com/temporalio/sdk-php/pull/336
- [ ] https://github.com/temporalio/sdk-php/pull/355
- [ ] Mentions about UUID, HistoryLength and visibility features from [v2.6.0 release](https://github.com/temporalio/sdk-php/releases/tag/v2.6.0) may be introduced in the documentation

**Comment by fairlydurable** [comment]
Closing
