### ISSUE TITLE
[ python ] Add code samples for missing content

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1790]
The following sections need code samples.

Provide a code sample per section by using the comment section to provide a code snippet.
Mark the checkbox complete as sample code is added.

If the language does not support a feature, write “NA” or link/code to a related concept: for an example, see Go’s [Remove Search Attribute](https://docs.temporal.io/application-development/observability?lang=go#remove-search-attribute).

## Testing

- [x] [Assert In Workflow](https://docs.temporal.io/application-development/testing?lang=python#assert-in-workflow)
- [ ] [Cancel An Activity](https://docs.temporal.io/application-development/testing?lang=python#cancel-an-activity)
- [x] [Listen To Heartbeats](https://docs.temporal.io/application-development/testing?lang=python#listen-to-heartbeats)
- [x] [Manual Method](https://docs.temporal.io/application-development/testing?lang=python#manual-method)
- [ ] [Mock Activities](https://docs.temporal.io/application-development/testing?lang=python#mock-activities)
- [x] [Run An Activity](https://docs.temporal.io/application-development/testing?lang=python#run-an-activity)
- [x] [Setting Up](https://docs.temporal.io/application-development/testing?lang=python#setting-up)
- [ ] [Skip Time In Activities](https://docs.temporal.io/application-development/testing?lang=python#skip-time-in-activities)
- [ ] [Skip Time](https://docs.temporal.io/application-development/testing?lang=python#skip-time)
- [x] [Test Activities](https://docs.temporal.io/application-development/testing?lang=python#test-activities)
- [x] [Test Frameworks](https://docs.temporal.io/application-development/testing?lang=python#test-frameworks)
- [x] [Test Workflows](https://docs.temporal.io/application-development/testing?lang=python#test-workflows)
- [ ] [Workflow Context](https://docs.temporal.io/application-development/testing?lang=python#workflow-context)

## Observability

- [ ] [Search Attributes](https://docs.temporal.io/application-development/observability#search-attributes)
- [ ] [Visibility](https://docs.temporal.io/application-development/observability#visibility)

## Features

- [ ] [Environment Variables](https://docs.temporal.io/application-development/features#environment-variables)
- [ ] [Mutable Side Effects](https://docs.temporal.io/application-development/features#mutable-side-effects)
- [ ] [Namespaces](https://docs.temporal.io/application-development/features#namespaces)
- [x] [Send Signal From Client](https://docs.temporal.io/application-development/features#send-signal-from-client)

**Comment by bergundy** [comment]
We should remove the namespaces and environment variables section from the guide IMO.
There's no support for mutable side effects in Python.

**Comment by rachfop** [comment]
Closing as it is tracked internally now.
