### ISSUE TITLE
[ Documentation request ] fix documentaion typo on Developer's guide - Foundations page

### ISSUE THREAD

**Issue by ShamilAssylbekov** [temporalio/documentation#1827]
# Brief description

`documentaion` typo on Developer's guide - Foundations page:
https://docs.temporal.io/application-development/foundations?lang=go#code-samples

```
❯ grep -R documentaion *
docs/application-development/foundations.md:- [Background Check application](https://github.com/temporalio/background-checks): Provides a non-trivial Temporal Application implementation in conjunction with [application documentaion](https://learn.temporal.io/examples/go/background-checks/).
docs-src/go/code-samples-go.md:- [Background Check application](https://github.com/temporalio/background-checks): Provides a non-trivial Temporal Application implementation in conjunction with [application documentaion](https://learn.temporal.io/examples/go/background-checks/).
```

#  Your recommended content

Please, fix the typo. I wasn't sure if this is supposed to be a bug report, or not, and I'll have a PR for fix coming shortly.

**Comment by flossypurse** [comment]
Thanks @ShamilAssylbekov - looks like this was resolved!
https://docs.temporal.io/application-development/foundations?lang=go#code-samples
