### ISSUE TITLE
Finish moving content from old Cluster deployment guide

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1903]
I've seen some things that I can't find elsewhere. Could someone go through the whole thing and copy missing info to current pages?

> We want to disperse the info in that file into the appropriate places in the new guides.

_Originally posted by @flossypurse in https://github.com/temporalio/documentation/pull/1861#discussion_r1085588520_

**Comment by flossypurse** [comment]
All self hosted cluster deployment info is either now here:

https://docs.temporal.io/self-hosted-guide
or here:
https://docs.temporal.io/clusters

The KB articles have been deprecated, and relevant info moved into the self-hosted or cloud prod deployments guides 

If there are specific things you want to see moving forward - feel free to create more issues.
