### ISSUE TITLE
[ Documentation request ] tctl workflow show/showid/describe/describeid

### ISSUE THREAD

**Issue by johanforssell** [temporalio/documentation#1929]
# Brief description

The tctl commands `tctl workflow show/showid/describe/describeid` all use the default namespace. This is **not** clear from the help text of the individual subcommands. They will not work as you think when you work in a namespace other than default (i.e. you'll not find any data).

The `--ns` flag also doesn't work on the subcommands, it needs to be set at the top level command. This seems odd to me.

#  Your recommended content

> Please remember to specify the namespace if querying a namespace other than **default**, e.g. 
`tctl --ns <NS> wf showid <WF_ID>`.

**Comment by rachfop** [comment]
tctl is being deprecated. 
I'll close this in favor of the Temporal CLI.
