### ISSUE TITLE
[ Documentation request ] How to connect to Temporal Cloud using Temporal CLI

### ISSUE THREAD

**Issue by Git-on-my-level** [temporalio/documentation#1978]
# Brief description
Currently it's unclear what the minimum set of environment variables are and how to populate them for Temporal Cloud. 

# Your recommended content
I actually haven't been able to use `Temporal CLI`with Temporal Cloud yet so I don't know, opening this issue to help prioritize getting this information to Temporal Cloud customers

**Comment by yahorbarkouski** [comment]
why this ticket is closed guys? is there any guide reference?
