### ISSUE TITLE
[suggestion] document all event types

### ISSUE THREAD

**Issue by sw-yx** [temporalio/documentation#198]
logging our internal discussion - suggesting to document all 40 event types to make them searchable

- https://github.com/temporalio/api/blob/7f074a51fff45a750e4eebe8dee2f0578c1a8197/temporal/api/enums/v1/event_type.proto#L35

basically i envision a one sentence/one para description of what each is and, if warranted, where they come from, what they might mean, and implications of the more rarely seen types

i'd put this in a json or yml file, and then pipe to docusaurus somewhere, because we might also want to use this exact mapping of descriptions inside Temporal Web

**Comment by flossypurse** [comment]
Just an update here - 
I tried to use Snipsync here as a quick win.
However, proto file linters don't like comments at the end of the files:
https://github.com/temporalio/api/pull/108

So, options are:
- Find a way to add an exception to the linter to work with Snipsync
- Alter Snipsync such that it only needs an opening wrapper somehow
- Just link directly to that file from the docs and add informational comments inline to the file (need to do this to use Snipsync anyways)
- Duplicate the list and document the events in another file somewhere

**Comment by sw-yx** [comment]
i think for our purposes we can just do 3 or 4 for now, and if we figure out how to do 1 or 2 in future we can double back

**Comment by flossypurse** [comment]
I think the best solution right now is to make sure there are comments directly in the proto file and then we can link to that file in Github. I created a Notion page to collect the comments.

**Comment by flossypurse** [comment]
Done!
https://github.com/temporalio/documentation/pull/296
