### ISSUE TITLE
[ Documentation request ] Add note in filestore archival that APIs are not supported

### ISSUE THREAD

**Issue by kyle-au** [temporalio/documentation#1985]
# Brief description

Filestore option for archival does not mention that it does not support APIs. This led us down a couple-days of troubleshooting when it was doomed from the start

#  Your recommended content

Current text:
> - **Local file system**: The [filestore archiver](https://github.com/temporalio/temporal/tree/master/common/archiver/filestore) is used to archive data in the file system of whatever host the Temporal server is running on. This provider is used mainly for local installations and testing and should not be relied on for production environments.

Recommended / Draft:
>- **Local file system**: The [filestore archiver](https://github.com/temporalio/temporal/tree/master/common/archiver/filestore) is used to archive data in the file system of whatever host the Temporal server is running on. In the case of [temporal helm-charts](https://github.com/temporalio/helm-charts), the archive data is stored in the `history` pod. APIs do not function with the filestore archive. This provider is used mainly for local installations and testing and should not be relied on for production environments.

**Comment by axfelix** [comment]
Handled in https://github.com/temporalio/documentation/pull/2389 -- thanks for reporting, and sorry for the confusion!
