### ISSUE TITLE
[ Bug report ] Link in docs to https://docs.temporal.io/workflows#queries does not find the anchor

### ISSUE THREAD

**Issue by mikepence** [temporalio/documentation#2002]
## Required

**What is the issue?**
Content such as https://docs.temporal.io/workflows#signal includes a link that points to https://docs.temporal.io/workflows#queries but that anchor does not exist in that page. Other instances of the incorrect URL may exist in other places, as well.

**How can we reproduce the issue?**
Attempt to browse to https://docs.temporal.io/workflows#queries

**What is the expected behavior?**
The URL should link to https://docs.temporal.io/workflows#query

## Additional context (optional—the more we know, the faster it goes)
See the content in https://docs.temporal.io/workflows#signal for an example of the link

**Screenshots:**
NA

**Browser and version:**
NA

**Device and screen size:**
NA

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/pull/2391 — thanks for reporting!
