### ISSUE TITLE
[ Documentation request ] Slack Link No Longer Valid

### ISSUE THREAD

**Issue by zhixinwen** [temporalio/documentation#2033]
# Brief description

slack channel in https://github.com/temporalio/temporal/blob/master/README.md is no longer valid

#  Your recommended content

Add your recommended content here. Add the content directly to this page or add links to drafts.
Documentation requests that are made without any recommendations could take longer to process.

**Comment by axfelix** [comment]
Closing as this appears to have been fixed -- the link is working currently.
