### ISSUE TITLE
[ Documentation request ] /references/web-ui-environment-variables `TEMPORAL_PUBLIC_PATH` should be `TEMPORAL_UI_PUBLIC_PATH`

### ISSUE THREAD

**Issue by washanhanzi** [temporalio/documentation#2076]
a typo in the web-ui env varibale

according to https://github.com/temporalio/ui-server/blob/5fb8b60fd0cef919354e45578e1025f96cac565a/docker/config-template.yaml#LL3C58-L3C58, the public path env variable should be `TEMPORAL_UI_PUBLIC_PATH`

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/pull/2390 — thanks for reporting!
