### ISSUE TITLE
[ Documentation request ] Example of single activity testing in Go

### ISSUE THREAD

**Issue by danthegoodman1** [temporalio/documentation#2173]
# Brief description

https://docs.temporal.io/dev-guide/go/testing#test-activities does not have an clear example of this, like the [typescript docs have](https://docs.temporal.io/dev-guide/typescript/testing#run-an-activity)

#  Your recommended content

An example similar to the [typescript docs](https://docs.temporal.io/dev-guide/typescript/testing#run-an-activity) that is concise and shows the minimum requirements to run an activity (with input)

**Comment by flossypurse** [comment]
Some info has been added here https://docs.temporal.io/dev-guide/go/project-setup#test-activity-code
