### ISSUE TITLE
[ Bug report ] Python tutorial has a couple of errors

### ISSUE THREAD

**Issue by z4ce** [temporalio/documentation#2292]
## Required

**What is the issue?**
In executing the python tutorial (https://learn.temporal.io/getting_started/python/hello_world_in_python/) I found a couple of errors.

First:
The section that has `touch tests/__init__.py` has an extra back tick. When copy and pasting you get an error.

Second:
The section the example file for `tests/test_run_worker.py` has been truncated and should have the following appended:

```
               id=str(uuid.uuid4()),
                task_queue=task_queue_name,
            )
```

**Screenshots:**
<img width="498" alt="image" src="https://github.com/temporalio/documentation/assets/4860914/b83395c8-b076-4e69-ac65-164d2132f1e1">

<img width="1088" alt="image" src="https://github.com/temporalio/documentation/assets/4860914/a1cc9e44-74f0-42c7-9d1b-68974f41e40b">

**Comment by axfelix** [comment]
Thanks for reporting this! It's been fixed in https://github.com/temporalio/temporal-learning/pull/119.
