### ISSUE TITLE
[ Documentation request ]  Automated install instructions for Windows using Scoop

### ISSUE THREAD

**Issue by tehmantra** [temporalio/documentation#2323]
# Brief description

[Temporal CLI installation instructions](https://docs.temporal.io/cli#installation) currently include a bash script, homebrew, or manual installation. 

For users on Windows, the only option is manual, which is not ideal.

Temporal CLI has been added to the [Scoop installer](https://scoop.sh/) main bucket (https://github.com/ScoopInstaller/Main/pull/4805) so Windows users can now install Temporal CLI easily.

```
PS> scoop install temporal-cli

Installing 'temporal-cli' (0.10.5) [64bit] from main bucket
Loading temporal_cli_0.10.5_windows_amd64.zip from cache
Checking hash of temporal_cli_0.10.5_windows_amd64.zip ... ok.
Extracting temporal_cli_0.10.5_windows_amd64.zip ... done.
Linking ~\scoop\apps\temporal-cli\current => ~\scoop\apps\temporal-cli\0.10.5
Creating shim for 'temporal'.
'temporal-cli' (0.10.5) was installed successfully!

PS> temporal --version

temporal version 0.10.5 (server 1.21.4) (ui 2.17.0)

PS> get-command temporal

CommandType     Name           Version    Source
-----------     ----           -------    ------
Application     temporal.exe   0.0.0.0    ~\scoop\shims\temporal.exe

```

#  Your recommended content

Add a new heading to the installation instructions section detailing how to install with scoop

``````md
### Scoop

Run the following command to install Temporal CLI using Scoop:

```
scoop install temporal-cli
```

``````

**Comment by rachfop** [comment]
This is a nice catch. Thank you!
