### ISSUE TITLE
Default WorkflowIDReusePolicy?

### ISSUE THREAD

**Issue by shaunco** [temporalio/documentation#233]
https://docs.temporal.io/docs/workflows#id-uniqueness says:
> The default is `AllowDuplicateFailedOnly`

https://github.com/temporalio/sdk-go/blob/3e18a77f4f15631ab151ce66ec600518603951ac/internal/client.go#L435 says:
>  Optional: defaulted to `AllowDuplicate`.

**Comment by alexshtin** [comment]
Thanks for reporting this. Doc is wrong  and needs to be fixed. Another good source of server enforced defaults for enums:
https://github.com/temporalio/temporal/blob/master/common/enums/defaults.go.

**Comment by flossypurse** [comment]
https://github.com/temporalio/documentation/pull/289
