### ISSUE TITLE
[ Documentation request ] Wrong link

### ISSUE THREAD

**Issue by froblesmartin** [temporalio/documentation#2340]
# Brief description

At https://docs.temporal.io/cloud/metrics#temporal-cloud-metrics-setup, the link from the piece of text
> [Data sources configuration for Temporal Cloud and SDK metrics in Grafana] (https://docs.temporal.io/cloud/metrics#data-sources-configuration-for-temporal-cloud-andssdk-metrics-in-grafana)

is wrong (one "s" instead of "-").

**Comment by TheOne04** [comment]
I would like to fix this.

**Comment by rachfop** [comment]
Got this merged in. Thanks!
