### ISSUE TITLE
[ Bug report ] Broken link to 'Java file processing example' in Task Routing doc

### ISSUE THREAD

**Issue by biewers2** [temporalio/documentation#2396]
## Required

**What is the issue?**

There's a broken link on the `Concepts > Workers` page.

`https://github.com/temporalio/samples-java/tree/master/src/main/java/io/temporal/samples/fileprocessing`

looks to have been changed to

`https://github.com/temporalio/samples-java/tree/main/core/src/main/java/io/temporal/samples/fileprocessing`

**How can we reproduce the issue?**

* Navigate to `Concepts > Workers > What is Task Routing? > Route Activity Tasks to a specific host`
* Click on the `Java file processing example` code samples link
* Receive a 404

**What is the expected behavior?**

To load the `fileprocessing` samples directory in the `samples-java` repo

## Additional context

**Screenshots:**
![Screenshot from 2023-10-14 09-25-01](https://github.com/temporalio/documentation/assets/24466993/7148bbb7-1491-4e3c-a5d3-f0d3acb1a1b2)

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/pull/2401, thank you for reporting!
