### ISSUE TITLE
[ Documentation request ] Minimum Retention Period 

### ISSUE THREAD

**Issue by Aoao54** [temporalio/documentation#2398]
# Brief description
[minimum Retention Period ](https://docs.temporal.io/clusters#retention-period)
In the doc , minimum Retention Period is 1 day. But I find it is wrong. The value can be 1h.
<img width="412" alt="image" src="https://github.com/temporalio/documentation/assets/84021683/8f7293af-a514-45cb-be33-dc61664a28b2">

#  Your recommended content
change it to the right value.

**Comment by rachfop** [comment]
[tctl is being deprecated](https://docs.temporal.io/tctl-v1)

From the temporal cli:

```
 --retention value Length of time (in days) a closed Workflow is preserved before deletion.
 ```
 
 Using the following command:
 
 ```
 temporal operator namespace create defaultv2 --retention
 ```
