### ISSUE TITLE
[ Bug report ] Links to java examples in Golang introduction dev-guide

### ISSUE THREAD

**Issue by jeromewir** [temporalio/documentation#2399]
## Required

**What is the issue?**

The two links `Documentation samples repository` and `Go SDK samples repository` in https://docs.temporal.io/dev-guide/go/introduction are redirecting to java examples instead of Golang.

**How can we reproduce the issue?**

Navigate to https://docs.temporal.io/dev-guide/go/introduction#additional-resources, click one of the two links mentionned above.

**What is the expected behavior?**

I believe the links should be the following:
- Documentation samples repository: https://github.com/temporalio/documentation-samples-go
- Go SDK samples repository: https://github.com/temporalio/samples-go

I believe the faulty file is there: https://github.com/temporalio/documentation/blob/3d783a8a0196fbf41e1d03a1af0474343384c1ed/docs/dev-guide/golang/introduction.md?plain=1#L154-L155

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

![CleanShot 2023-10-16 at 13 00 22@2x](https://github.com/temporalio/documentation/assets/5878807/f7d3002e-654d-4639-8a84-9c9a3d236ec7)

**Browser and version:**

**Device and screen size:**

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/pull/2400, thank you for reporting!
