### ISSUE TITLE
[ Documentation request ] please add to doc that activities are not re-executed  (during replay) after their completion is recorded in even history

### ISSUE THREAD

**Issue by antmendoza** [temporalio/documentation#2430]
<img width="896" alt="Screenshot 2023-10-24 at 15 17 30" src="https://github.com/temporalio/documentation/assets/514932/f6a7929e-5d62-4620-a12f-c5c9d5efea62">

**Comment by rachfop** [comment]
Thanks for the ping. We are tracking and discussing this internally.

**Comment by axfelix** [comment]
Fixed in https://github.com/temporalio/documentation/pull/2432!
