### ISSUE TITLE
Wrong module name in go-hello-world

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/documentation#245]
In the Go Hello World [tutorial](https://github.com/temporalio/documentation/blob/master/docs/go-hello-world.md), the module name at the following steps is wrong:

https://docs.temporal.io/docs/go-hello-world#worker
https://docs.temporal.io/docs/go-hello-world#workflow-starter

The [instructions](https://docs.temporal.io/docs/go-hello-world#scaffold-go-project) create module `hello-world-project/app`

But the subsequent [worker code](https://docs.temporal.io/docs/go-hello-world#worker) and [start code](https://docs.temporal.io/docs/go-hello-world#workflow-starter) depend on `hello-world-project-template-go/app`

**Comment by flossypurse** [comment]
Thanks for pointing this out!
Indeed, aligning these makes for a better experience.
Changes are up: https://github.com/temporalio/documentation/pull/267
