### ISSUE TITLE
[ TypeScript Documentation Bug report ] Broken Link on Website

### ISSUE THREAD

**Issue by ctriley** [temporalio/documentation#2460]
## Required

**What is the issue?**

https://docs.temporal.io/dev-guide/typescript/observability?lang=typescript#visibility links to https://typescript.temporal.io/api/classes/proto.temporal.api.workflowservice.v1.workflowservice-1/#listworkflowexecutions

On the line Use [WorkflowService.listWorkflowExecutions](https://typescript.temporal.io/api/classes/proto.temporal.api.workflowservice.v1.workflowservice-1/#listworkflowexecutions):

It results in a 404

**What is the expected behavior?**
It should result in a web page detailing the documentation for that function.

**Comment by axfelix** [comment]
Good catch, should be linking to https://typescript.temporal.io/api/classes/proto.temporal.api.workflowservice.v1.WorkflowService-1#listworkflowexecutions
