### ISSUE TITLE
Documentation Enhancement - Activity Registration

### ISSUE THREAD

**Issue by rajrahul** [temporalio/documentation#253]
## Expected Behavior
Documentation Enhancement

## Actual Behavior

1. Multiple Activity registration overwrites the previously registered Activities 
worker.registerActivitiesImplementations(new ActivityA());
worker.registerActivitiesImplementations(new ActivityB());
worker.registerActivitiesImplementations(new ActivityC());

This following approach works as expected. Since there can be only one registration it must be documented. 
worker.registerActivitiesImplementations(new ActivityA(), new ActivityB(), new ActivityC());

2. If I have multiple activities with the same activity method name, it throws that activity is registered already.

**Comment by flossypurse** [comment]
This PR aims to explicitly mention how to do this for each language:
https://github.com/temporalio/documentation/pull/284

**Comment by flossypurse** [comment]
PR has landed!
