### ISSUE TITLE
Stale content in "Accessing Activity Info" chapter

### ISSUE THREAD

**Issue by shabalin** [temporalio/documentation#258]
Direct link:
https://docs.temporal.io/docs/java-implementing-activities#accessing-activity-info

> The Activity class provides ...

 The current Activity class implementation doesn't provide neither `Activity.getNamespace()` nor `Activity.getWorkflowExecution()` static methods.

So the link is completely misleading.  Also, it's not obvious how to actually get the workflow information (e.g. Memo content) from within the activity method.
what I could quickly come to:
```java
        ActivityExecutionContext ctx = Activity.getExecutionContext();
        ListOpenWorkflowExecutionsResponse response = workflowClient().getWorkflowServiceStubs().blockingStub()
            .listOpenWorkflowExecutions(
                ListOpenWorkflowExecutionsRequest.newBuilder()
                    .setNamespace(NAMESPACE)
                    .setExecutionFilter(
                        WorkflowExecutionFilter.newBuilder()
                            .setWorkflowId(ctx.getInfo().getWorkflowId())
                            .setRunId(ctx.getInfo().getRunId())
                            .build()
                    )
                    .build());

        String name = null;
        if(response.getExecutionsCount()==1) {
            WorkflowExecutionInfo e = response.getExecutions(0);
            if (e.getMemo().getFieldsMap() != null && e.getMemo().getFieldsMap().get(NAME_FIELD) != null) {
                Payload payload = e.getMemo().getFieldsMap().get(NAME_FIELD);
                if (payload.getData() != null) {
                    try {
                        DataConverter dataConverter = DataConverter.getDefaultInstance();
                        name = dataConverter.fromPayload(payload, String.class, String.class);
                    } catch (Exception exception) {
                        // ignore
                    }
                }
            }
        }
        LOG.debug("Task name: {}", name);
```

Would you mind to advise if there is an easier way?

**Comment by flossypurse** [comment]
@vitarb recommendations?

**Comment by flossypurse** [comment]
Thanks for reporting this!
This PR aims to update that information and examples: https://github.com/temporalio/documentation/pull/275
You are correct in that you must use `Activity.getExecutionContext()` - and then from the `ActivityExecutionContext` you can get the `ActivityInfo` where you can use `getWorkflowId()` and list Workflows using that Id.
Listing Workflows should provide you with the Memo content.
