### ISSUE TITLE
[ Documentation request ] A worker with multiple workflows but the interceptor only work for a certain workflow

### ISSUE THREAD

**Issue by YufeeXing** [temporalio/documentation#2725]
# Brief description

In your sample repo, I find a example that a Temporal worker with 2 workflows https://github.com/temporalio/samples-typescript/blob/main/snippets/src/workflows.ts

In this situation, if I also want to add interceptors for the worker, Can I specify the interceptors only work on a certain workflow ignore other workflows?

Or I need to set up more than 1 workers for this situation? Each worker only bind to a workflow?

#  Your recommended content

Add your recommended content here. Add the content directly to this page or add links to drafts.
Documentation requests that are made without any recommendations could take longer to process.

**Comment by flossypurse** [comment]
I recommend asking this question either on [community.temporal.io](https://community.temporal.io) or in our [community Slack](https://join.slack.com/t/temporalio/shared_invite/zt-2fvfkbppj-5zXRX5_WPXQwOdGjamcSlA)
