### ISSUE TITLE
Add examples for passing struct arg via Signal 

### ISSUE THREAD

**Issue by leowmjw** [temporalio/documentation#283]
As per https://community.temporal.io/t/deserialization-error-for-signal-struct/1609/2; there is a need to have a more complete example for passing in a struct via signal.

Should I add an example here? --> https://github.com/temporalio/documentation/blob/master/docs/go-signals.md

**Comment by flossypurse** [comment]
Yes, you are more than welcome to add the example to that page - add me as a reviewer on any PR you put up.
