### ISSUE TITLE
Outdated document for default token key provider

### ISSUE THREAD

**Issue by phuongdnguyen** [temporalio/documentation#3032]
# Brief description

Default token key provider mentioned [here](https://github.com/temporalio/documentation.git) is probably renamed to `defaultTokenKeyProvider` along with its constructor `NewDefaultTokenKeyProvider`.

#  Your recommended content
Temporal provides an `defaultTokenKeyProvider`. This component dynamically obtains public keys that follow the [JWKS format](https://tools.ietf.org/html/rfc7517). Use `defaultTokenKeyProvider` with RSA requires only the `RsaKey` and `Close` methods.

```
provider := authorization.NewDefaultTokenKeyProvider(cfg, logger)
```

**Comment by napcs** [comment]
@foodatbar thanks for submitting. We'll investigate!

**Comment by phuongdnguyen** [comment]
Hi @napcs, is this actually completed ?
