### ISSUE TITLE
[ Bug report ] Schedule-To-Close Timeout in "Core application" links to Start-To-Close in "Encyclopedia"

### ISSUE THREAD

**Issue by roxit** [temporalio/documentation#3083]
**What is the issue?**

In "How to set the required Activity Timeouts" sections of all `Docs > Develop > xxx SDK > Core application` pages, "Schedule-To-Close Timeout" incorrectly links to "Start-To-Close Timeout" in Encyclopedia.

**How can we reproduce the issue?**

Go to the follow pages, check the target of the closest "Schedule-To-Close Timeout" link, `#start-to-close-timeout` should be replaced with `#schedule-to-close-timeout`.

* https://docs.temporal.io/develop/go/core-application#required-timeout
* https://docs.temporal.io/develop/java/core-application#required-timeout
* https://docs.temporal.io/develop/php/core-application#required-timeout
* https://docs.temporal.io/develop/python/core-application#required-timeout
* https://docs.temporal.io/develop/typescript/core-application#required-timeout
* https://docs.temporal.io/develop/dotnet/core-application#activity-execution

**Comment by fairlydurable** [comment]
All links checked. Corrections are appropriate and work.

**Comment by fairlydurable** [comment]
Thank you for your work on fixing this bug. We really appreciate it!
