### ISSUE TITLE
[ Documentation request ] Explain what "slot" is

### ISSUE THREAD

**Issue by artemik** [temporalio/documentation#3192]
# Brief description

Temporal [worker performance](https://docs.temporal.io/develop/worker-performance#worker-executor-slots-sizing) docs mention "slots", but don't explain what slot is and how it relates to threads or anything else. Docs should explain it.

#  Your recommended content

-

**Comment by fairlydurable** [comment]
Thank you for submitting this issue. Does this [link](https://docs.temporal.io/develop/worker-performance#slots) help on the Worker Performance page? If so, I'll close the ticket.

We appreciate all feedback.

**Comment by fairlydurable** [comment]
Closing ticket as done. Thank you again for the suggestion.

**Comment by artpaym** [comment]
Hi @fairlydurable I see you've added some information regarding slots, thanks.

However could you also explain how it relates to threads in Java? The docs mention considerations regarding resources, CPU etc, but it's hard to judge about it for me as a user without realizing how it translates to threads, which is one of the major factors for Java.

**Comment by artemik** [comment]
Hi @fairlydurable I see you've added some information regarding slots, thanks.

However could you also explain how it relates to threads in Java? The docs mention considerations regarding resources, CPU etc, but it's hard to judge about it for me as a user without realizing how it translates to threads, which is one of the major factors for Java.

**Comment by fairlydurable** [comment]
@artemik Can you create a new issues so we can track this? Thank you
