### ISSUE TITLE
[Feature Request] Document TEMPORAL_DEBUG environment variable to assist in better debugging experience

### ISSUE THREAD

**Issue by mobiletoly** [temporalio/documentation#346]
**Is your feature request related to a problem? Please describe.**
Workflow fails with PotentialDeadlockException during debugging of workflows

**Describe the solution you'd like**
Temporal Java SDK has TEMPORAL_DEBUG environment variable that can be set to prevent workflow from throwing exceptions and provide better debugging experience. Unfortunately Temporal's Java SDK documentation is missing documenting this behavior as of now.

**Comment by tsurdilo** [comment]
@mobiletoly thanks for opening the feature request!
