### ISSUE TITLE
When running workflows/activities in testing environment temporal throws panic timeout 3s

### ISSUE THREAD

**Issue by yevgenypats** [temporalio/documentation#489]
## Expected Behavior

To run successfully

## Actual Behavior

```
--- FAIL: Test_Workflow (3.00s)
panic: test timeout: 3s, workflow stack: coroutine root [blocked on chan-2.Receive]:
```

## Steps to Reproduce the Problem

Reproduction repository - https://github.com/yevgenypats/bug-repro

```
git clone  https://github.com/yevgenypats/bug-repro
go test .
```

I've added essentially a wait inside the activity and even though I've 10 seconds timeout in `StartToCloseTimeout` the test will always panic after 3 seconds. Anyidea? It essentially makes the testing infrastructure un-usable.

**Comment by flossypurse** [comment]
Current testing info is here: https://docs.temporal.io/docs/go/testing
To start we can add it there.

But per our coverage plan, we will probably want to have something like "How to test Workflows in Go"
