### ISSUE TITLE
Add all `tctl` commands

### ISSUE THREAD

**Issue by robholland** [temporalio/documentation#499]
**Describe the bug**
The `tctl` page should mention (even if briefly) all `tctl` commands.

**To Reproduce**
1. Go to 'https://docs.temporal.io/docs/system-tools/tctl'
2. Notice that `tctl admin workflow delete` is not mentioned on the page.

**Expected behavior**
All `tctl` commands should be mentioned, even if only very briefly.

**Comment by flossypurse** [comment]
I would strongly argue that missing content is a documentation coverage issue, not a bug.
But, point taken.

**Comment by robholland** [comment]
Noted for future :)

**Comment by flossypurse** [comment]
Just providing some visibility - here are some changes we have made over the last couple of months in regards to documenting tctl:
- https://github.com/temporalio/documentation/pull/692
- https://github.com/temporalio/documentation/pull/687
- https://github.com/temporalio/documentation/pull/736
- https://github.com/temporalio/documentation/pull/751

**Comment by flossypurse** [comment]
https://github.com/temporalio/documentation/pull/772
