### ISSUE TITLE
Possible relative link issue

### ISSUE THREAD

**Issue by flossypurse** [temporalio/documentation#510]
**Describe the bug**
"Deterministic runtime" link seems to be relative and doesn't work in some cases.

**To Reproduce**
Per @dnr 

if you do this:
1. follow this link: https://docs.temporal.io/docs/node/introduction
2. click "hello world in node" on the left
3. url gets rewritten client-side to this: https://docs.temporal.io/docs/node/hello-world
4. scroll down and click "deterministic runtime"
5. it works
but if you do this:
1. follow this link: https://docs.temporal.io/docs/node/hello-world
2. 301 redirect to same url but with a trailing slash
3. scroll down and click "deterministic runtime"
4. 404 (because it's a relative path and the "directory" is different)

**Expected behavior**

Not to reach a 404 page.

**Comment by dnr** [comment]
Is it worth trying to avoid the trailing-slash urls entirely? Seems like that could cause problems elsewhere too
