### ISSUE TITLE
Home page - "Microservices Orchestration" section text and link

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#593]
<img width="413" alt="Screen Shot 2021-08-28 at 6 36 54 PM" src="https://user-images.githubusercontent.com/119422/131232641-909be3bf-3124-494f-9ed7-2665832159ed.png">

"Human-in-the-loop steps in case of failure":
1. I think this is called just Human interactions/decision making. Also it's not only in case of failure but any decision (activity invocation) can have a human decision involved with it imo (calling a human decision service).
2. The page section this "human-in-the-loop" link goes to says "human intervention step in the case of failure" so there is becomes "intervention", if possible let's at least try to keep those 2 consistent.
Thanks!

**Comment by sw-yx** [comment]
as spoken offline
