### ISSUE TITLE
Home Page - large open space between top section and use cases

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#594]
On the home page the top section with the title, getting started, video link and the sample code is pretty tightly packed.
After that there is an unnatural change of having a ton of space in the next two sections:

<img width="1342" alt="Screen Shot 2021-08-28 at 6 47 01 PM" src="https://user-images.githubusercontent.com/119422/131232823-21ed436a-8466-4023-bf1a-34c6035059de.png">

It it possible to move those up a little by removing some of the space between things? It looks weird at least to me the way it is now.

**Comment by sw-yx** [comment]
as spoken offline
