### ISSUE TITLE
Home Page - use different colors for actual links and highlighted text

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#595]
On the home page we currently use the same color text for links, as well as text that i supposed is meant to be highlighted but is actually not a link. This imo is very confusing. For example here:

<img width="585" alt="Screen Shot 2021-08-28 at 6 50 48 PM" src="https://user-images.githubusercontent.com/119422/131232885-7e329cf8-d484-4d33-ba57-62f9241e162d.png">

Those are not links (the greenish text) but have the same color as actual links on the same page.

**Comment by sw-yx** [comment]
as spoken offline
