### ISSUE TITLE
Home Page - Temporal logo looks tiny

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#596]
<img width="1319" alt="Screen Shot 2021-08-28 at 6 54 34 PM" src="https://user-images.githubusercontent.com/119422/131232920-78dcfe4e-4f9c-4a19-9d41-b5f8154e06ce.png">

Temporal logo looks tiny compared to the rest of the text / sections on the page.

**Comment by sw-yx** [comment]
as spoken offline
