### ISSUE TITLE
Home Page - unify the button links (color)

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#597]
<img width="368" alt="Screen Shot 2021-08-28 at 6 56 54 PM" src="https://user-images.githubusercontent.com/119422/131232961-1a03b80a-a16f-44a4-9d23-be0587f5fcab.png">
<img width="360" alt="Screen Shot 2021-08-28 at 6 56 43 PM" src="https://user-images.githubusercontent.com/119422/131232962-27d8c5fa-0169-41a2-b9f0-5971765eb500.png">
<img width="348" alt="Screen Shot 2021-08-28 at 6 56 38 PM" src="https://user-images.githubusercontent.com/119422/131232963-d13cf091-b05b-4f93-8221-46f66951444c.png">
<img width="339" alt="Screen Shot 2021-08-28 at 6 57 48 PM" src="https://user-images.githubusercontent.com/119422/131232967-174a3bc6-c5ce-4fff-9b01-4d3640c82961.png">

why are they different? :)

**Comment by sw-yx** [comment]
as spoken offline
