### ISSUE TITLE
Home page - Temporal section

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/documentation#598]
<img width="1370" alt="Screen Shot 2021-08-28 at 6 59 48 PM" src="https://user-images.githubusercontent.com/119422/131232991-4ff95b78-e3ac-4fb6-8126-c19816f413fa.png">

For people not familiar with Temporal this section not having like a "About Temporal" or some similar title is confusing.
When I looked at this page for the first time before joining I had 0 clue if Maxim and Samar are customers or users of Temporal or what , especially since section above shows the name title **and** company of the people that made the statements :)

**Comment by sw-yx** [comment]
as spoken offline
