### ISSUE TITLE
[Bug] Data Convert API link doesn't show relevant info

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/documentation#617]
### To Reproduce

1. Go to https://docs.temporal.io/docs/concepts/workers/#workers-can-be-encrypted-in-transit-and-at-rest
2. Click on `Data Converter API` link, copying here: [Data Converter API](https://docs.temporal.io/docs/java/activities/#activity-interface)
3. Shows up Java's SDK activity interface page which doesn't have any info on data converter API 

### Expected behavior

Should show up info specifically on Data Converter API and not necessarily for Java SDK

### Versions

- OS: [e.g. Mac, Windows, Linux]
- Temporal Version [e.g. 1.7.0?]
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by flossypurse** [comment]
I updated this link to go here for now: https://docs.temporal.io/docs/content/what-is-a-data-converter

1 - this page will be deprecated soon.
2 - we still have to add and map to SDK specific implementation examples for custom data converters in the docs.

I think this solves the immediate issue of going somewhere completely irrelevant - mind if I close?

**Comment by feedmeapples** [comment]
@flossypurse sounds good!
