### ISSUE TITLE
[Feature Request] Document how to call workflows across the different SDKs

### ISSUE THREAD

**Issue by bergundy** [temporalio/documentation#632]
See more info in the original issue: https://github.com/temporalio/sdk-node/issues/228

CC: @joebowbeer moved this here.

**Comment by flossypurse** [comment]
Two things we will probably want to do here:
1.  Create new "What is an External Workflow?" page and answer
2. How to start, signal, query, request cancellation, or terminate External Workflows sections in each of those "How tos"
