### ISSUE TITLE
[Feature Request] Expand Node External Deps 

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#647]
### Is your feature request related to a problem? Please describe.

When I read the current page:

https://docs.temporal.io/docs/node/external-dependencies

questions that come to mind are:

1. When would I want to use different apply modes
2. What does passing a reference look like

### Describe the solution you'd like

Adding content to speak to #1 and show an example of #2.

**Comment by aarohib** [comment]
@lorensr is this still an issue? 
@sw-yx could you provide some context here?

**Comment by lorensr** [comment]
No more node, and no more external deps 😄 Sink docs make sense 👍
