### ISSUE TITLE
[Feature Request] Add information about data converters and compatible changes to data classes

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/documentation#655]
Right now some of the users may not even realize how the serialization works and Temporal are not taking care of it directly.
We should list all default data converters that we support

```
    new ByteArrayPayloadConverter(),
    new ProtobufJsonPayloadConverter(),
    new JacksonJsonPayloadConverter()
```

 and how to use them (by setting encoding type).

We should provide information on how the default converters can be customized, for example by providing more relaxed options to Jackson mapper or adding language/library specific modules.
We also should explicitly tell that maintaining the compatibility of different versions of data classes is the user's responsibility and is specific to a combination of a serializer and its configuration that they use.

This request is intended for JavaSDK and is motivated by this issue: https://github.com/temporalio/sdk-java/issues/328
But it should also be relevant to other SDKs.

**Comment by lorensr** [comment]
I think it would make sense to have a data converter section of the dev guide, containing lang-specific details on the default data converter and how to use a custom data converter. For TS, the content would include:

https://legacy-documentation-sdks.temporal.io/typescript/data-converters

**Comment by axfelix** [comment]
Closing this while cleaning up old Documentation issues -- it's being looked into as part of https://temporalio.atlassian.net/browse/EDU-1184.

**Comment by axfelix** [comment]
Closing this -- `Converters and Codecs` sections have been added to most of our dev guides.
