### ISSUE TITLE
[Bug] [Documentation Links] Hello World Sample link broken

### ISSUE THREAD

**Issue by rupalivohra** [temporalio/documentation#666]
### To Reproduce

1. Visit https://docs.temporal.io/docs/node/introduction/#step-1-create-a-new-project
2. Click on "the basic Hello World sample" or "sample for connecting to a Temporal Server instance secured with mTLS"
3. Get redirected to Page Not Found

### Expected behavior

I expect the links to work. Unfortunately, I'm not sure exactly where they're meant to link to; the file structure within the [NodeSDK repo](https://github.com/temporalio/sdk-node/tree/main/packages/create-project) seems pretty different from wherever those links are pointing.

**Comment by flossypurse** [comment]
Ya, just checked these links again, and they all seem to be working OK.
I am going to close this for now, but please reopen if issues persist.
