### ISSUE TITLE
[go] Side effect doc incorrect statement about activities

### ISSUE THREAD

**Issue by vikstrous2** [temporalio/documentation#671]
https://github.com/temporalio/documentation/blob/master/docs/go/side-effect.md
> unlike the Temporal guarantee of at-most-once execution for Activities

https://github.com/temporalio/documentation/blob/master/docs/go/activities.md#activity-timeouts
> Temporal guarantees that Activities are executed at least once

I'm pretty sure the activities doc is the correct one, so the side effect doc's warning about gurantees can either be removed or reworded to not imply that the activity guarantees are different.

**Comment by sw-yx** [comment]
cc @dtornow mind taking a look? sounds like your cup of tea

**Comment by flossypurse** [comment]
Closing in favor of https://github.com/temporalio/documentation/issues/709
