### ISSUE TITLE
[Feature Request] advanced docs on using Rust Core SDK

### ISSUE THREAD

**Issue by swyxio** [temporalio/documentation#679]
### Is your feature request related to a problem? Please describe.

as discussed with Roey who wantd to have an advanced page for this

also: we can explain how to work directly with node / ts-node / nodemon

**Comment by bergundy** [comment]
We should show an example of how to set up statsd for metrics as requested here: https://github.com/temporalio/sdk-typescript/issues/327

**Comment by flossypurse** [comment]
@sw-yx @lorensr @bergundy can you all detail some specifics here?
Is there a way we can break this down into some more concrete asks?
Do you have any drafted content we can look at to help us understand the needs?

**Comment by sw-yx** [comment]
sorry for delay - this task is for @bergundy to do, not for docs team

**Comment by axfelix** [comment]
Closing since this is handled in new docs + SDK feature matrix.
