### ISSUE TITLE
[Feature Request] Document SDK versioning scheme

### ISSUE THREAD

**Issue by bergundy** [temporalio/documentation#705]
As discussed on slack with @mfateev and @Spikhalskiy we'd like to apply a semver incompatible versioning scheme for SDKs.
Temporal SDKs can break compatibility in either public APIs or history incompatibility.
We'd like to reserve major version changes to history incompatible changes, that is, if you deploy this new version your running workflows could stop running and you'll run into determinism errors.
We'll use the minor for API breaking changes and patch for new features and bugfixes.

**Comment by flossypurse** [comment]
@bergundy is there a concrete ask of the docs team on this yet?
Have you all decided on what the version schema is for each SDK?

**Comment by bergundy** [comment]
We'll come up with an accurate description of the schema and update. We haven't really gotten back to this discussion since October.

**Comment by axfelix** [comment]
@bergundy What's the current status of this?

**Comment by axfelix** [comment]
We could probably link more to these Github changelogs, I think they're the source of truth on this right now: https://github.com/temporalio/sdk-go/releases

These are linked from https://docs.temporal.io/dev-guide/java/introduction#updates, but hard to find.

**Comment by bergundy** [comment]
We've had some internal discussions solidifying our scheme but have not had the time to come up with a document yet.
