### ISSUE TITLE
[Feature Request] Go activity documentation should mention struct-level registration

### ISSUE THREAD

**Issue by cretz** [temporalio/documentation#710]
### Is your feature request related to a problem? Please describe.

https://github.com/temporalio/documentation/blob/1b6e1075b201ac5ebf35b7983fa6b315f694b482/docs/go/activities.md?plain=1#L89 doesn't explain registering an activity struct like https://pkg.go.dev/go.temporal.io/sdk/worker#ActivityRegistry does.

### Describe the solution you'd like

Explain you can use `RegisterActivity` for a struct and all exported methods will be registered.

**Comment by flossypurse** [comment]
@aarohib - I would add this info here:
https://github.com/temporalio/documentation/blob/master/docs/go/how-to-develop-a-worker-program-in-go.md

We call out our recommendation to write Activities as Structs here: https://github.com/temporalio/documentation/blob/master/docs/go/how-to-develop-an-activity-definition-in-go.md

**Comment by aarohib** [comment]
@tsurdilo

**Comment by flossypurse** [comment]
Curious @cretz - hoping you can clarify what it looks like to customize the Name of the Activity Method when they are part of a struct - and you are registering the whole struct?
Looks like if I want to customize the Name of the Activity function I need to use `RegisterActivityOptions` like this:
```
// ...
w := worker.New(temporalClient, "your_task_queue_name", worker.Options{})
registerOptions := activity.RegisterOptions{
  Name: "CoolActivityTypeName",
  // ...
}
w.RegisterActivityWithOptions(YourActivity, registerOptions)
// ...
```

If the thing being registered is a function - I see how this works.
But if the thing being registered is a struct - then what am I customizing in this example?
Is it not possible or would I have to register each method individually? But then the Worker wouldn't have access to the exported fields on the struct?

**Comment by cretz** [comment]
From https://pkg.go.dev/go.temporal.io/sdk/worker#ActivityRegistry above `RegisterActivityWithOptions`:

```
	// When registering the structure that implements activities the name is used as a prefix that is
	// prepended to the activity method name.
	//  worker.RegisterActivityWithOptions(&Activities{ ... }, RegisterActivityOptions{Name: "MyActivities_"})
	// To override each name of activities defined through a structure register the methods one by one:
	// activities := &Activities{ ... }
	// worker.RegisterActivityWithOptions(activities.SampleActivity1, RegisterActivityOptions{Name: "Sample1"})
	// worker.RegisterActivityWithOptions(activities.SampleActivity2, RegisterActivityOptions{Name: "Sample2"})
```

**Comment by flossypurse** [comment]
> From https://pkg.go.dev/go.temporal.io/sdk/worker#ActivityRegistry above `RegisterActivityWithOptions`:
> 
> ```
> 	// When registering the structure that implements activities the name is used as a prefix that is
> 	// prepended to the activity method name.
> 	//  worker.RegisterActivityWithOptions(&Activities{ ... }, RegisterActivityOptions{Name: "MyActivities_"})
> 	// To override each name of activities defined through a structure register the methods one by one:
> 	// activities := &Activities{ ... }
> 	// worker.RegisterActivityWithOptions(activities.SampleActivity1, RegisterActivityOptions{Name: "Sample1"})
> 	// worker.RegisterActivityWithOptions(activities.SampleActivity2, RegisterActivityOptions{Name: "Sample2"})
> ```

Of course, thanks, not sure how I missed that.
