### ISSUE TITLE
[Feature Request] Document SDK metrics across all SDKs

### ISSUE THREAD

**Issue by bergundy** [temporalio/documentation#713]
Sources listed here:
https://github.com/temporalio/sdk-java/blob/3deccf2c50b1bdb9f41cd2b385ee4dce402acf82/temporal-sdk/src/main/java/io/temporal/internal/metrics/MetricsType.java#L22
https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-serviceclient/src/main/java/io/temporal/serviceclient/MetricsType.java#L22
https://github.com/temporalio/sdk-go/blob/master/internal/common/metrics/constants.go
https://github.com/temporalio/sdk-core/blob/9a9599da26692b7fdff4cf6d81d343f19bfeb18e/src/telemetry/metrics.rs

The doc should also include a section per SDK on how to configure metrics to be exported and high level insights that could be gained from these metrics.

**Comment by flossypurse** [comment]
- https://github.com/temporalio/documentation/issues/851

**Comment by flossypurse** [comment]
This reference documents SDK metrics across SDKs: https://docs.temporal.io/docs/reference/sdk-metrics/

Specific issues listed above have been created to track the progress for each SDK specific "how to".
