### ISSUE TITLE
[Feature Request] Workflow Concept page should contain a word "determinism"

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/documentation#716]
I would expect that Workflow Concept page (https://docs.temporal.io/docs/concepts/workflows) contains the usage of "determinism" and some explanation of the concept or a link to it. But the is nothing about determinism on the page. The only references to determinism could be found in the language-specific SDK documentation and a bit on the Activities Concept page, which is counterintuitive. The workflow page avoids the concept of determinism, but Activities page jumps right into it and uses it as a main defining block.

Also, currently, Workflow Concept page (https://docs.temporal.io/docs/concepts/workflows) starts with a section
"Example subscription use-case" which looks off for a Concept page.

**Comment by mfateev** [comment]
I think that determinism is an important concept, but it doesn't belong to the concepts page.  Some SDKs like Typescript one provide a fully deterministic runtime. So user doesn't really need to know about this.

**Comment by Spikhalskiy** [comment]
Short summary of the discussion with @mfateev:

1. Typescript documentation shouldn't mention determinism explicitly much. We probably can leave [Determinism](https://docs.temporal.io/docs/typescript/determinism/) section there, but it needs to be clearly marked as implementation details that are not needed for people who just rump up, it shouldn't be in main API related pages.
2. Concept pages can either
- try to fully hide and don't reference a concept of Determinism anywhere. But in that case, the Activities concept page needs to introduce Activities without reference to Deterministic Workflows [Max's option] Motivation: let's minimize the amount of mandatory concepts to understand for people who just start
- Introduce Determinism on Workflow page as an important concept and go full into referencing it, but we should explicitly mark that Typescript developers can "skip" these sections as non-important for them. [Dmitry's option] Motivation: "Workflow" is a broken abstraction anyway and people need to understand Determinism to understand replayability, understand why side effects should be in Activities, etc. And also it's the reason for limitations in some languages (like what shouldn't be used in workflow code).

We agreed that both solutions are fine, but it needs to be either first or second. We can't avoid Determinism on Workflows page and suddenly use it on the Activities page.

**Comment by Sushisource** [comment]
I'll throw in here that I do think we need to have determinism in the concepts section. It is true that ideally the user doesn't have to know, but the practical reality is they very often do. Even with TS' deterministic runtime (which even then can still be broken, it's not bulletproof), how do we explain *why* you can't use certain libraries/functions? How do we explain how workflow time isn't wall clock time? Things like these require that the determinism concept be explained at a high level.

It needn't be one of the first things we introduce to users, but I do think it does need to be addressed conceptually.

**Comment by bergundy** [comment]
I didn't get Temporal until Ryland explained that we replay history using deterministic code to materialize program state.

**Comment by tsurdilo** [comment]
Question is what's the percentage of workflow code that all our users write that ends up being not deterministic.
I would argue to say it's very small percentage, and the list of do's/don't's is imo sufficient.

**Comment by tsurdilo** [comment]
To add, I agree that we should have this in the docs :) 
Just I feel that we use the docs as a crush for our SDKs where we should have non-determinism validation built in.

**Comment by Spikhalskiy** [comment]
@tsurdilo I personally think that close to 100% of workflows that are written by our users are potentially non-deterministic.
For example, I'm kinda positive that almost all of them have an external configuration for anything real-in-production. And I don't think most users carefully persist configuration into side effects. Most likely, they don't.

I personally think that Determinism is leaking from all abstractions and it will be really hard to work with Temporal in production (and prevent and resolve actual production problems) without actually understanding the concept.

**Comment by aarohib** [comment]
https://www.notion.so/temporalio/February-3-2022-e35a2702b0994bf081654e5ee84e0892

**Comment by Sushisource** [comment]
Cross posting this I wrote in Slack. I think we really need to address this.

Even in Typescript you can easily screw things up by not understanding what constitutes a compatible change to workflow code.

> So something I just realized while writing some versioning designs.... We describe at least occasionally what it means to be nondeterministic in a workflow in the sense that the same code will do different things depending on its inputs/environment.

> Do we ever describe what it means to be nondeterministic by changing code? Not only is that super important to tell you when you need to use versioning apis or a different task q, it's also probably the most frequent source of user bug reports IME.

**Comment by flossypurse** [comment]
Content has been published https://github.com/temporalio/documentation/pull/931

https://docs.temporal.io/docs/concepts/what-is-a-workflow-definition/

Thank you all for the input! Thank you @Sushisource for providing a great starting point and awesome examples.
