### ISSUE TITLE
[Bug] list item with embedded img shows up misplaced

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/documentation#724]
### To Reproduce

1. Go to https://docs.temporal.io/docs/typescript/introduction/
2. See `SDK source` (3rd item in the top most list) with the github stars img shows up misplaced

### Screenshots/Terminal output

![image](https://user-images.githubusercontent.com/11838981/140199515-06ea230d-64c0-471c-9fdd-403b95f928d5.png)

### Versions

- OS: [e.g. Mac, Windows, Linux]
- Temporal Version [e.g. 1.7.0?]
- Are you using Docker or Kubernetes or building Temporal from source?

### Additional context

`.prose img` applies margin to the image and breaks how the list is shown
![image](https://user-images.githubusercontent.com/11838981/140199983-4cf8b0f4-c00b-4bd3-9bc5-ca1982453d0a.png)

**Comment by sw-yx** [comment]
fixed w separate pr
