### ISSUE TITLE
[Feature Request] Document that Go query handling should not mutate workflow state

### ISSUE THREAD

**Issue by cretz** [temporalio/documentation#726]
### Is your feature request related to a problem? Please describe.

Java SDK, TypeScript SDK, and the concept documentation make it clear not to mutate state inside a query handler, but Go SDK documentation does not.

### Describe the solution you'd like

Go SDK docs warn like the others.

**Comment by DJSanti** [comment]
I'm pretty sure I addressed this here: https://github.com/temporalio/documentation/pull/1070

**Comment by DJSanti** [comment]
If this isn't sufficient enough to close it, I'll see to it.
