### ISSUE TITLE
[Request] Include constraint in docs?

### ISSUE THREAD

**Issue by brheringer** [temporalio/documentation#741]
On the [java-sdk workshop](https://www.youtube.com/watch?v=VoSiIwkvuX0), at time 23:08, class `GreetingWorkflowImpl.java` is shown with a comment: 
`"You can add workflow methods inside signal methods (like call activities)... but its not recomended."`

I asked why it is not recommended. I understood the answer was because Temporal was not designed to deal with errors on activities outside the workflow execution method.

Based on that, here is my question/request. Should it be included as an "Workflow Implementation Constraints" on documentation? It sounds important to me.

https://github.com/temporalio/documentation/blob/master/docs/java/workflows.md
Section: Workflow Implementation Constraints

**Comment by tsurdilo** [comment]
+1, also I think most users do not know they can use workflow api inside signal methods. We could add that in the docs as well, as there are some use cases for this at times.

**Comment by tsurdilo** [comment]
@flossypurse i can work on this if that's ok.
