### ISSUE TITLE
[Bug] Small text color contrast/mismatches bugs in dark mode

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [temporalio/documentation#763]
### Describe the bug

Filing an issue for several related visual bugs in dark mode:

* When a right sidebar heading that contains code is selected, the code is a blue on blue background (example: https://docs.temporal.io/docs/typescript/workflows#sleep)
* Link code text is an [inaccessible](https://webaim.org/articles/contrast) black on blue (example: https://docs.temporal.io/docs/typescript/workflows#the-continueasnew-api)
* `RelatedReadList` text is an [inaccessible](https://webaim.org/articles/contrast) white on green text (example: https://docs.temporal.io/docs/typescript/workflows#parent-close-policy)

### To Reproduce

1. Enable dark mode on docs.temporal.io
2. See links above

### Expected behavior

Visible text with strong color contrast.

### Screenshots/Terminal output

![Blue on blue code heading text](https://user-images.githubusercontent.com/3335181/143627570-3d4be063-2e11-40df-8228-531f3fbd7108.png)

![Black on blue code link text](https://user-images.githubusercontent.com/3335181/143627688-153a7999-fe9f-4153-99a3-27b0bff93025.png)

![White on green related link text](https://user-images.githubusercontent.com/3335181/143627731-c86569e1-6681-47bb-9e20-5435c1408424.png)

### Versions

N/A

**Comment by flossypurse** [comment]
These issues are now fixed!
Many design targeted updates have been released in the past few weeks - let us know what you think.
