### ISSUE TITLE
[Feature Request] Clarify continue-as-new signal draining for Go

### ISSUE THREAD

**Issue by cretz** [temporalio/documentation#781]
### Is your feature request related to a problem? Please describe.

At https://docs.temporal.io/docs/concepts/workflows#faq, there is a note for continue-as-new that says:

> If you are using Signals with the Go SDK, you should make sure to do an asynchronous drain on the Signal channel or the Signals will be lost.

But it is not in the Go docs that I can find

### Describe the solution you'd like

In the Go documentation for continue-as-new and maybe also for signals, this same thing should be mentioned

**Comment by flossypurse** [comment]
Thanks @cretz !
Per our feature specification plan - what we are probably looking at doing here is refining answers to the following questions:
- What is Continue-As-New
- How to use Continue-As-New in Go

Can you point us to examples for Go that shows as "asynchronous drain" on the Signal channel?
What does it mean to drain the channel - what are the consequences if you do not? That kind of context would be helpful if you have it.

**Comment by cretz** [comment]
> what we are probably looking at doing here is refining answers to the following questions:

Understood. In this tiny issue though, I was just pointing out there's a Go note in the non-Go section that isn't even in the Go section. I think this note can be added to the Go section before taking on the larger task of clarifying.

> Can you point us to examples for Go that shows as "asynchronous drain" on the Signal channel?

https://github.com/temporalio/samples-go/issues/158 has been opened to add the sample.

> What does it mean to drain the channel - what are the consequences if you do not? That kind of context would be helpful if you have it.

It means there isn't a signal in buffer. This is unique to how Go handles signals I believe (others use callbacks). My understanding is you can lose signals if you continue-as-new before handling all locally buffered signals.

**Comment by mastermanu** [comment]
We should also warn against the following usage issue highlighted here: https://github.com/temporalio/sdk-go/issues/197

In essence, if the workflow is kicked off via a string, then continue-as-new should also use a string vs using the method pointer. otherwise you see weird behavior where continue-as-new starts a different workflow.
