### ISSUE TITLE
[Feature Request] Add Go troubleshooting page

### ISSUE THREAD

**Issue by cretz** [temporalio/documentation#790]
### Is your feature request related to a problem? Please describe.

Developers running workflows in Go don't know how to debug or what the common bugs are.

### Describe the solution you'd like

Create a page (or pages) to clarify how to debug an existing history (e.g. using replayer, setting `TEMPORAL_DEBUG=1` env var for stepping, etc), what are common cases of errors, and what is needed by Temporal team to help diagnose issues.

**Comment by axfelix** [comment]
Closing since there's been a lot of work around this in the last 2 years and we're currently developing a course on error handling.
