### ISSUE TITLE
Update What is a Workflow Id Reuse Policy & extract other info

### ISSUE THREAD

**Issue by flossypurse** [temporalio/documentation#799]
Per this thread: (screen  shot captured to preserve longer than Slack)
https://temporalio.slack.com/archives/CTRCR8RBP/p1640050211132400

![Screen Shot 2021-12-22 at 7 40 06 AM](https://user-images.githubusercontent.com/34380806/147109554-799d7e9f-cf16-4840-bedf-6635979ab2fc.png)
![Screen Shot 2021-12-22 at 7 40 28 AM](https://user-images.githubusercontent.com/34380806/147109600-4f97666b-ea2d-44fd-a89e-16a20cdc0438.png)

**Comment by flossypurse** [comment]
@dtornow feel free to add here if we are missing anything.
Any ideas for a diagram ? ;)

**Comment by natalie-zamani** [comment]
@flossypurse Thanks for opening an issue on this!

**Comment by tsurdilo** [comment]
this question has been answered on forum multiple times already before this slack thread. and in a more understandable way imo as well. should we preserve those too?

**Comment by flossypurse** [comment]
Yes, 100%.
Can you add the links here?
