### ISSUE TITLE
Extract troubleshooting info for ES

### ISSUE THREAD

**Issue by flossypurse** [temporalio/documentation#842]
Per this slack thread: https://temporalio.slack.com/archives/CTRCR8RBP/p1642723886348800

References this community thread: https://community.temporal.io/t/unable-error-when-doing-add-search-attribute/3533

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/150850975-f824a4a2-3c4d-40ff-856e-d39bb51f78e2.png)
![image](https://user-images.githubusercontent.com/6764957/150851008-a9394b50-5d00-4d9d-8ad7-46af2162f924.png)
![image](https://user-images.githubusercontent.com/6764957/150851035-80aa5dd6-7f87-4ec9-bdac-4c0a9dd381fd.png)
![image](https://user-images.githubusercontent.com/6764957/150851059-792adc84-1cac-451b-aad9-43a39a6019c3.png)
![image](https://user-images.githubusercontent.com/6764957/150851083-db4eb6eb-d7a9-4187-9c0f-a60520e641f8.png)

**Comment by aarohib** [comment]
https://community.temporal.io/t/how-to-best-handle-mysterious-context-deadline-exceeded-502-errors/2689

**Comment by axfelix** [comment]
There was a recent post in this community thread, so it appears to still be an outstanding issue — probably belongs in https://docs.temporal.io/cluster-deployment-guide#elasticsearch.
