### ISSUE TITLE
Remove misleading TypeScript continue-as-new sentence

### ISSUE THREAD

**Issue by cretz** [temporalio/documentation#850]
### Is your feature request related to a problem? Please describe.

At https://docs.temporal.io/docs/typescript/workflows/#the-continueasnew-api we say:

> Note that this is done immediately, so pending updates from Signals must be drained before proceeding or data may be lost.

This is a bit misleading, because in Go you actually have to "drain" but what this is really trying to say is "Continue as new throws out of the function immediately, so anything unhandled will not be processed". This then applies to signals added to some kind of pending queue, or activity results still being waited on, or whatever.

### Describe the solution you'd like

Either remove the sentence entirely or replace just explaining that continue-as-new throws immediately. There is nothing signal-specific here.

**Comment by djmagee** [comment]
Fixed in #872.
