### ISSUE TITLE
Create how to configure Java SDK metrics

### ISSUE THREAD

**Issue by aarohib** [temporalio/documentation#852]
Sources:

https://github.com/temporalio/sdk-java/blob/3deccf2c50b1bdb9f41cd2b385ee4dce402acf82/temporal-sdk/src/main/java/io/temporal/internal/metrics/MetricsType.java#L22
https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-serviceclient/src/main/java/io/temporal/serviceclient/MetricsType.java#L22

**Comment by flossypurse** [comment]
@Spikhalskiy curious if you can show us an example of how someone might "configure Java SDK" metrics -
What does it mean to "configure metrics" - i.e. what are the configurable aspects?

**Comment by Spikhalskiy** [comment]
@flossypurse 
This is the relevant forum answer: https://community.temporal.io/t/how-to-enable-metrics-support-using-java-sdk/366/2?u=spikhalskiy
And we have a sample for metrics: https://github.com/temporalio/samples-java/tree/main/src/main/java/io/temporal/samples/metrics

> what are the configurable aspects?
Almost none, I think the doc may just show how to wire the PrometheusRegistry into java sdk. Configuration of PrometheusRegistry is not the business of our docs really.

**Comment by Spikhalskiy** [comment]
Yeah, it can be closed now, covered by #1315
