### ISSUE TITLE
Create how to configure TypeScript SDK metrics

### ISSUE THREAD

**Issue by aarohib** [temporalio/documentation#853]
Source:
https://github.com/temporalio/sdk-core/blob/9a9599da26692b7fdff4cf6d81d343f19bfeb18e/src/telemetry/metrics.rs

**Comment by flossypurse** [comment]
Some info published here https://docs.temporal.io/docs/typescript/production-deploy/#logging-and-metrics

**Comment by flossypurse** [comment]
Closing, we also have: https://docs.temporal.io/application-development/observability/?lang=typescript#metrics
New or other specific issues can be tracked separately.
