### ISSUE TITLE
[Bug] Correct comment about continue as new behaviour of example

### ISSUE THREAD

**Issue by robholland** [temporalio/documentation#861]
### Describe the bug

The comment at https://github.com/temporalio/documentation/blob/master/docs/typescript/workflows.md?plain=1#L958 is confusing because the continue as new only happens after the loop exits. The `condition` does not automatically cause a continue as new, it just ensures that we don't block for longer than a day waiting for updates for a single loop iteration. Also suggest that the MAX_ITERATIONS should be set to higher than 1, because that's a non-sensical value in the context of demonstrating continue as new.

I would suggest updating the comment to something like "Ensure we don't block forever waiting for updates. This means that we can be sure we will eventually continue as new even if we don't receive updates.".

**Comment by sw-yx** [comment]
that comment was from @bergundy  will let him consider
