### ISSUE TITLE
Clarification is needed for "What is an Activity Id" page

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/documentation#864]
> A unique Id that identifies an Activity that is executing. 

Unique in which scope?
Why "is executing"? Can we identify an activity that finished executing? If we can't, why?

**Comment by flossypurse** [comment]
> Unique in which scope?
> Why "is executing"? Can we identify an activity that finished executing? If we can't, why?

Love it - any suggestions for the answers to these?

**Comment by axfelix** [comment]
Fixed in a more recent version of docs: https://docs.temporal.io/activities#activity-id
