### ISSUE TITLE
[Request] document `tctl admin wf delete`

### ISSUE THREAD

**Issue by sw-yx** [temporalio/documentation#878]
### Is your feature request related to a problem? Please describe.

a user asked how to delete a wf and we had no docs to point them to.

https://temporalio.slack.com/archives/CTRCR8RBP/p1644302381664009

### Describe the solution you'd like

lets document it

**Comment by flossypurse** [comment]
Ya, Dail is working on the tctl reference - admin commands are coming soon.
This is a duplicate issue of https://github.com/temporalio/documentation/issues/499
