### ISSUE TITLE
[Feature Request] Give advice on Activity length

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#890]
### Is your feature request related to a problem? Please describe.

A couple users have been uncertain how much to put in a single Activity versus breaking it into multiple Activities. 

### Describe the solution you'd like

It would be helpful to have a concepts page/section on that architecture decision. The pros/cons of each, and example use cases. 

### Additional context

https://github.com/temporalio/documentation/pull/882#issuecomment-1035875835

**Comment by sw-yx** [comment]
worth pointing to this as well https://github.com/andreasasprou/temporal-url-batch-scraping
