### ISSUE TITLE
[Bug] TypeScript introduction wrongly mentions the 'Hello, Temporal!' string will be printed at the CLI

### ISSUE THREAD

**Issue by iampava** [temporalio/documentation#893]
### What are you really trying to do?

I'm trying to follow the Getting Started part of the Docs regarding TypeScript: https://docs.temporal.io/docs/typescript/introduction/

### Describe the bug

The docs mention that running the workflow will output `Hello, Temporal!` to the CLI:

![image](https://user-images.githubusercontent.com/11327761/153838828-588b6994-2e6d-4f98-8499-568202fb0b17.png)

However, this is only true if the user uncomments this `console.log` from the Hello World example: https://github.com/temporalio/samples-typescript/blob/main/hello-world/src/client.ts#L25-L26

**Comment by lorensr** [comment]
@flossypurse sure, feel free to assign things to me 😊

@iampava thanks for reporting! Fixed in https://github.com/temporalio/samples-typescript/commit/630b7a99d5bc7933eb660d2252b6dac383791a3f
