### ISSUE TITLE
[Bug] Link on blog post 2021-04-20-why-rust-powers-core-sdk is no longer valid

### ISSUE THREAD

**Issue by calum-stripe** [temporalio/documentation#921]
### What are you really trying to do?

Was reading the blog and kicked the link here: [state machine for timers](https://github.com/temporalio/sdk-core/blob/master/src/machines/timer_state_machine.rs). This is now out of date (I'm guessing the file moved)

The page no longer exists. (see above link)

### Minimal Reproduction
Click the link above ^^ 

### Environment/Versions
production?

**Comment by djmagee** [comment]
@Sushisource or @vitarb, do you happen to know where the cited link in https://docs.temporal.io/blog/why-rust-powers-core-sdk should point now?
