### ISSUE TITLE
How to configure TLS for the internal System Worker

### ISSUE THREAD

**Issue by flossypurse** [temporalio/documentation#933]
TLS docs are missing description of [SystemWorker settings](https://github.com/temporalio/temporal/blob/c121a7d3bcba00da97fc29244243a6fd17c95aee/common/config/config.go#L116) that were introduced a year ago to simplify configuration of TLS for the worker service. This was discovered while working on [this PR](https://github.com/temporalio/temporal/pull/2036) that got merged. The PR added a new property ForceTLS to ClientTLS. We need to add it to the docs as well after it’s released, presumably with 1.14. Let me know if you need help with how to describe these settings.

**Comment by anilkvasireddy** [comment]
Can you please provide some high level documentation on it.

**Comment by jrpedrianes** [comment]
Hi, 

I'm looking for documentation about this configuration and I just found this issue. 

Does somebody know if this configuration is "hidden" for some reason, is it a configuration that is better not to use?

Thank you very much.
