### ISSUE TITLE
[Bug] list-search-attributes

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#963]
On latest tctl (1.15.1), there is no `cluster list-search-attributes`

```
$ tctl cluster list-search-attributes
No help topic for 'list-search-attributes'
$ tctl cluster -h
NAME:
   tctl cluster - Operate Temporal cluster

USAGE:
   tctl cluster command [command options] [arguments...]

COMMANDS:
   health, h                   Check health of frontend service
   get-search-attributes, gsa  List search attributes that can be used in list workflow query
```

https://github.com/temporalio/documentation/blob/master/docs/tctl/cluster/list-search-attributes.md

**Comment by djmagee** [comment]
Right you are, @lorensr. Because I'm in the process of creating the tctl reference, I'm working from `temporalio/tctl/cli` rather than from `temporalio/tctl/cli_curr`. The former becomes the source for releases in the near future.
